##### import os
import re
import gc
import sqlite3
import unicodedata
import random
import math

import numpy as np
import pandas as pd

from difflib import SequenceMatcher
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score

DATA_DIR = "/home/sagemaker-user/Igniters_submission_file"
OUTPUT_DIR = os.path.join(DATA_DIR, "output")

DB_PATH = os.path.join(DATA_DIR, "entity_index.db")

os.makedirs(OUTPUT_DIR, exist_ok=True)

RANDOM_SEED = 42
random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)

print("Pipeline environment ready.")
print("Database:", DB_PATH)

In [19]:
def normalize_text(value):
    if pd.isna(value):
        return ""

    text = str(value).lower()

    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode("ascii")

    text = text.replace("&", " and ")

    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text


def normalize_series(series):
    return series.fillna("").astype(str).map(normalize_text)


def first_token(text):
    text = normalize_text(text)

    if not text:
        return ""

    return text.split()[0]


def name_prefix(text, n=4):
    text = normalize_text(text)

    if not text:
        return ""

    return text[:n]


def address_tokens(text):
    text = normalize_text(text)

    if not text:
        return []

    return [
        token for token in text.split()
        if len(token) >= 5
    ]


print("Normalization functions ready.")

Normalization functions ready.

In [20]:
if os.path.exists(DB_PATH):
    print("Existing database found:")
    print(DB_PATH)
    print("If this is from an incomplete previous run, delete it before continuing.")
else:
    print("No existing database. Ready to build.")

Existing database found:
/home/sagemaker-user/Igniters_submission_file/entity_index.db
If this is from an incomplete previous run, delete it before continuing.

In [21]:
conn = sqlite3.connect(DB_PATH)

cursor = conn.cursor()

cursor.execute("""
CREATE TABLE IF NOT EXISTS entities (
    entity_id TEXT PRIMARY KEY,
    source TEXT NOT NULL,
    business_name TEXT,
    business_address TEXT,
    country TEXT,
    clean_name TEXT,
    clean_address TEXT
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS name_prefix_index (
    block_key TEXT,
    entity_id TEXT
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS first_token_index (
    block_key TEXT,
    entity_id TEXT
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS address_token_index (
    block_key TEXT,
    entity_id TEXT
)
""")

conn.commit()

print("SQLite schema created.")

SQLite schema created.

In [12]:
cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_name_prefix
ON name_prefix_index(block_key)
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_first_token
ON first_token_index(block_key)
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_address_token
ON address_token_index(block_key)
""")

cursor.execute("""
CREATE INDEX IF NOT EXISTS idx_entities_id
ON entities(entity_id)
""")

conn.commit()

print("SQLite indexes created.")

SQLite indexes created.

In [10]:
# Cell: Memory-safe chunk processor

CHUNK_SIZE = 25_000   # smaller chunk = lower RAM usage


def process_source_file(filepath, source_name):
    print(f"\nProcessing {source_name}")
    print(f"File: {filepath}")

    total = 0

    for chunk in pd.read_csv(
        filepath,
        sep="\t",
        dtype="string",
        chunksize=CHUNK_SIZE
    ):
        # Fill missing values
        chunk = chunk.fillna("")

        # Normalize name and address
        chunk["clean_name"] = normalize_series(chunk["business_name"])
        chunk["clean_address"] = normalize_series(chunk["business_address"])

        # ---------------------------------------------------------
        # 1. Insert main entity records
        # ---------------------------------------------------------

        records = []

        for row in chunk.itertuples(index=False):

            records.append((
                str(row.entity_id),
                source_name,
                str(row.business_name),
                str(row.business_address),
                str(row.country),
                str(row.clean_name),
                str(row.clean_address)
            ))

        conn.executemany(
            """
            INSERT OR REPLACE INTO entities
            (
                entity_id,
                source,
                business_name,
                business_address,
                country,
                clean_name,
                clean_address
            )
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            records
        )

        # ---------------------------------------------------------
        # 2. Create blocking records
        # ---------------------------------------------------------

        prefix_records = []
        first_records = []
        address_records = []

        for row in chunk.itertuples(index=False):

            entity_id = str(row.entity_id)
            country = normalize_text(row.country)
            name = str(row.clean_name)
            address = str(row.clean_address)

            # -----------------------------------------------------
            # Name prefix block
            # -----------------------------------------------------

            if country and name:

                prefix = name[:4]

                if prefix:
                    prefix_records.append(
                        (country + "|" + prefix, entity_id)
                    )

                # -------------------------------------------------
                # First word block
                # -------------------------------------------------

                name_parts = name.split()

                if name_parts:

                    first = name_parts[0]

                    if len(first) >= 3:
                        first_records.append(
                            (country + "|" + first, entity_id)
                        )

            # -----------------------------------------------------
            # Address token block
            # -----------------------------------------------------

            if country and address:

                tokens = address.split()

                used = set()

                for token in tokens:

                    # Ignore very short tokens
                    if len(token) < 5:
                        continue

                    # Ignore pure numbers
                    if token.isdigit():
                        continue

                    # Avoid duplicate tokens
                    if token in used:
                        continue

                    used.add(token)

                    address_records.append(
                        (country + "|" + token, entity_id)
                    )

                    # Maximum 3 address tokens per business
                    if len(used) >= 3:
                        break

        # ---------------------------------------------------------
        # 3. Insert blocking indexes
        # ---------------------------------------------------------

        if prefix_records:

            conn.executemany(
                """
                INSERT INTO name_prefix_index
                (block_key, entity_id)
                VALUES (?, ?)
                """,
                prefix_records
            )

        if first_records:

            conn.executemany(
                """
                INSERT INTO first_token_index
                (block_key, entity_id)
                VALUES (?, ?)
                """,
                first_records
            )

        if address_records:

            conn.executemany(
                """
                INSERT INTO address_token_index
                (block_key, entity_id)
                VALUES (?, ?)
                """,
                address_records
            )

        # Save this chunk
        conn.commit()

        total += len(chunk)

        # Free memory
        del records
        del prefix_records
        del first_records
        del address_records
        del chunk

        gc.collect()

        # Progress
        if total % 250_000 < CHUNK_SIZE:
            print(f"Processed {total:,} rows")

    print(f"\nFinished {source_name}: {total:,} rows")

In [14]:
process_source_file(
    os.path.join(DATA_DIR, "train_source2.tsv"),
    "S2"
)

Processing S2
File: /home/sagemaker-user/Igniters_submission_file/train_source2.tsv
Processed 250,000 rows
Processed 500,000 rows
Processed 750,000 rows
Processed 1,000,000 rows
Processed 1,250,000 rows
Processed 1,500,000 rows
Processed 1,750,000 rows
Processed 2,000,000 rows
Processed 2,250,000 rows
Processed 2,500,000 rows
Processed 2,750,000 rows
Processed 3,000,000 rows
Processed 3,250,000 rows
Processed 3,500,000 rows
Processed 3,750,000 rows
Processed 4,000,000 rows
Processed 4,250,000 rows
Processed 4,500,000 rows
Processed 4,750,000 rows
Processed 5,000,000 rows

Finished S2: 5,034,616 rows

In [15]:
print("\nDatabase verification after S2")

tables = [
    "entities",
    "name_prefix_index",
    "first_token_index",
    "address_token_index"
]

for table in tables:
    count = conn.execute(
        f"SELECT COUNT(*) FROM {table}"
    ).fetchone()[0]

    print(f"{table}: {count:,}")

Database verification after S2
entities: 5,034,616
name_prefix_index: 9,248,862
first_token_index: 8,618,084
address_token_index: 24,461,807

In [16]:
duplicate_count = conn.execute("""
    SELECT COUNT(*)
    FROM (
        SELECT entity_id
        FROM entities
        GROUP BY entity_id
        HAVING COUNT(*) > 1
    )
""").fetchone()[0]

print("Duplicate entity IDs:", duplicate_count)

Duplicate entity IDs: 0

In [22]:
process_source_file(
    os.path.join(DATA_DIR, "train_source3.tsv"),
    "S3"
)

Processing S3
File: /home/sagemaker-user/Igniters_submission_file/train_source3.tsv
Processed 250,000 rows
Processed 500,000 rows
Processed 750,000 rows
Processed 1,000,000 rows
Processed 1,250,000 rows
Processed 1,500,000 rows
Processed 1,750,000 rows
Processed 2,000,000 rows
Processed 2,250,000 rows
Processed 2,500,000 rows
Processed 2,750,000 rows
Processed 3,000,000 rows
Processed 3,250,000 rows
Processed 3,500,000 rows
Processed 3,750,000 rows
Processed 4,000,000 rows
Processed 4,250,000 rows
Processed 4,500,000 rows
Processed 4,750,000 rows
Processed 5,000,000 rows
Processed 5,250,000 rows

Finished S3: 5,285,603 rows

In [23]:
# Cell: Final database verification after S3

print("\n" + "=" * 50)
print("DATABASE VERIFICATION AFTER S3")
print("=" * 50)

tables = [
    "entities",
    "name_prefix_index",
    "first_token_index",
    "address_token_index"
]

for table in tables:
    count = conn.execute(
        f"SELECT COUNT(*) FROM {table}"
    ).fetchone()[0]

    print(f"{table}: {count:,}")

print("\nExpected entity count:")
print("S2:    5,034,616")
print("S3:    5,285,603")
print("Total: 10,320,219")

==================================================
DATABASE VERIFICATION AFTER S3
==================================================
entities: 10,320,219
name_prefix_index: 14,290,822
first_token_index: 13,321,683
address_token_index: 38,165,217

Expected entity count:
S2:    5,034,616
S3:    5,285,603
Total: 10,320,219

In [24]:
# Cell: Check Source 2 and Source 3 distribution

print("\n" + "=" * 50)
print("SOURCE DISTRIBUTION")
print("=" * 50)

source_counts = pd.read_sql_query("""
    SELECT source, COUNT(*) AS count
    FROM entities
    GROUP BY source
    ORDER BY source
""", conn)

print(source_counts.to_string(index=False))

print("\nExpected:")
print("S2:", f"{5_034_616:,}")
print("S3:", f"{5_285_603:,}")
print("Total:", f"{10_320_219:,}")

==================================================
SOURCE DISTRIBUTION
==================================================
source   count
    S2 5034616
    S3 5285603

Expected:
S2: 5,034,616
S3: 5,285,603
Total: 10,320,219

In [25]:
# Cell: Load a representative S1 sample and ground truth

S1_SAMPLE_SIZE = 20_000

print("Loading S1 sample...")

s1_sample = pd.read_csv(
    os.path.join(DATA_DIR, "train_source1.tsv"),
    sep="\t",
    dtype="string",
    nrows=S1_SAMPLE_SIZE
).fillna("")

ground_truth_sample = pd.read_csv(
    os.path.join(DATA_DIR, "train_ground_truth.tsv"),
    sep="\t",
    dtype="string",
    nrows=S1_SAMPLE_SIZE
).fillna("")

print("\nS1 sample shape:", s1_sample.shape)
print("Ground truth sample shape:", ground_truth_sample.shape)

print("\nS1 columns:")
print(s1_sample.columns.tolist())

print("\nGround truth columns:")
print(ground_truth_sample.columns.tolist())

print("\nFirst 3 S1 records:")
print(s1_sample.head(3).to_string(index=False))

print("\nFirst 3 ground truth records:")
print(ground_truth_sample.head(3).to_string(index=False))

Loading S1 sample...

S1 sample shape: (20000, 4)
Ground truth sample shape: (20000, 2)

S1 columns:
['entity_id', 'business_name', 'business_address', 'country']

Ground truth columns:
['source1_entity_id', 'matched_entity_ids']

First 3 S1 records:
   entity_id       business_name                       business_address country
S1-925783039 Orelee's Barbershop 1795 Westchester Drive, High Point, NC      US
S1-773889195         Prime Money        17560 Ellis Road, Tahlequah, OK      US
S1-377745466       B+ Retail Inc    1712 Montebello Avenue, Phoenix, AZ      US

First 3 ground truth records:
source1_entity_id                                              matched_entity_ids
        S1-965667 S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
      S1-55344266             S2-249013014,S2-197070651,S3-478195123,S3-384364074
     S1-343815751                          S2-790675320,S2-479876582,S3-878454467

In [26]:
# Cell: Align ground truth with the S1 sample

# Create a lookup from Source 1 ID -> ground-truth matches
gt_lookup = dict(
    zip(
        ground_truth_sample["source1_entity_id"],
        ground_truth_sample["matched_entity_ids"]
    )
)

# Keep only S1 records whose IDs exist in the sampled ground truth
s1_sample["matched_entity_ids"] = (
    s1_sample["entity_id"]
    .map(gt_lookup)
    .fillna("")
)

print("S1 sample shape:", s1_sample.shape)

print("\nS1 records with ground truth available:",
      (s1_sample["matched_entity_ids"] != "").sum())

print("S1 records with no match:",
      (s1_sample["matched_entity_ids"] == "").sum())

print("\nSample after alignment:")
print(
    s1_sample[
        ["entity_id", "business_name", "country", "matched_entity_ids"]
    ].head(10).to_string(index=False)
)

S1 sample shape: (20000, 5)

S1 records with ground truth available: 174
S1 records with no match: 19826

Sample after alignment:
   entity_id                            business_name country matched_entity_ids
S1-925783039                      Orelee's Barbershop      US
S1-773889195                              Prime Money      US
S1-377745466                            B+ Retail Inc      US
S1-133037285                            Christ Chapel      US
S1-755362802                  Prabhav Business Center   India
S1-851869949               Custom Wealth Services LLC      US
S1-785847572 Consulting Nyasa Nursing Private Limited   India
 S1-27541239                        Nexus Anchor Rain      US
S1-629417405                        Moore Bitwise Inc      US
 S1-22305073               Dermatology Green Medicine      US

In [27]:
# Cell: Create correctly aligned evaluation sample

EVAL_SIZE = 20_000

print("Loading ground truth...")

gt_all = pd.read_csv(
    os.path.join(DATA_DIR, "train_ground_truth.tsv"),
    sep="\t",
    dtype="string"
).fillna("")

print("Ground truth rows:", f"{len(gt_all):,}")

# Randomly select ground-truth records
gt_eval = gt_all.sample(
    n=EVAL_SIZE,
    random_state=RANDOM_SEED
).copy()

# IDs we need from Source 1
eval_ids = set(gt_eval["source1_entity_id"])

print("Selected evaluation IDs:", f"{len(eval_ids):,}")

del gt_all
gc.collect()

# Now read Source 1 in chunks and retrieve only those IDs
s1_eval_parts = []

for chunk in pd.read_csv(
    os.path.join(DATA_DIR, "train_source1.tsv"),
    sep="\t",
    dtype="string",
    chunksize=25_000
):
    matches = chunk[chunk["entity_id"].isin(eval_ids)]

    if len(matches) > 0:
        s1_eval_parts.append(matches)

    if sum(len(x) for x in s1_eval_parts) >= EVAL_SIZE:
        break

s1_eval = pd.concat(
    s1_eval_parts,
    ignore_index=True
).fillna("")

# Attach ground truth by entity ID
gt_lookup = dict(
    zip(
        gt_eval["source1_entity_id"],
        gt_eval["matched_entity_ids"]
    )
)

s1_eval["matched_entity_ids"] = (
    s1_eval["entity_id"]
    .map(gt_lookup)
    .fillna("")
)

print("\n" + "=" * 50)
print("EVALUATION SAMPLE")
print("=" * 50)

print("S1 evaluation rows:", f"{len(s1_eval):,}")
print(
    "Rows with ground truth:",
    f"{(s1_eval['entity_id'].isin(eval_ids)).sum():,}"
)

print(
    "Rows with at least one match:",
    f"{(s1_eval['matched_entity_ids'] != '').sum():,}"
)

print(
    "Rows with zero matches:",
    f"{(s1_eval['matched_entity_ids'] == '').sum():,}"
)

print("\nFirst 10 records:")
print(
    s1_eval[
        ["entity_id", "business_name", "country", "matched_entity_ids"]
    ].head(10).to_string(index=False)
)

Loading ground truth...
Ground truth rows: 2,206,821
Selected evaluation IDs: 20,000

==================================================
EVALUATION SAMPLE
==================================================
S1 evaluation rows: 20,000
Rows with ground truth: 20,000
Rows with at least one match: 18,881
Rows with zero matches: 1,119

First 10 records:
   entity_id                   business_name country                                                                                                           matched_entity_ids
S1-708796012       Board of Consumer Affairs      US                                                S2-994438467,S2-440628035,S3-338279058,S3-335174066,S3-703951662,S3-974934575
S1-387694500    Bombay Power Private Limited   India S2-89272121,S2-828925482,S2-960848454,S2-674345300,S3-789542813,S3-9126403,S3-469722658,S3-904486811,S3-77197957,S3-91755708
S1-973233920         Data Materials Networks      US                                                                          S2-428307002,S3-110090880,S3-159133847,S3-792460305
S1-769172378 Technocast Chit Private Limited   India                                                                                       S2-977119232,S2-754328130,S2-713014713
S1-436985273                  Corner Pilates      US                                                                                                    S2-488930867,S3-150259143
S1-287666599            Bates Generation LLC      US                                                             S2-207356341,S2-107690465,S2-594570026,S3-517645522,S3-737314411
S1-131038804  Torres Heartland Northland LLC      US                                                                          S2-655191371,S3-766103665,S3-508705806,S3-193182438
S1-460033462    FYJ Apparels Private Limited   India                                                                                        S2-985336551,S3-68319127,S3-280691790
S1-942301043              Qunaque Realty LLC      US                                                                                       S2-789520489,S2-438042920,S3-932179721
S1-535787043             Summit Freight P.C.      US

In [ ]:
# Cell: Candidate generation functions

def get_candidates_for_s1(row):
    """
    Retrieve potential S2/S3 matches using the SQLite blocking indexes.
    """

    entity_id = str(row["entity_id"])
    country = normalize_text(row["country"])
    name = normalize_text(row["business_name"])
    address = normalize_text(row["business_address"])

    candidate_ids = set()

    # -------------------------------------------------
    # 1. Name prefix block
    # -------------------------------------------------
    if country and name:
        prefix = name[:4]

        if prefix:
            rows = conn.execute(
                """
                SELECT entity_id
                FROM name_prefix_index
                WHERE block_key = ?
                """,
                (country + "|" + prefix,)
            ).fetchall()

            candidate_ids.update(r[0] for r in rows)

    # -------------------------------------------------
    # 2. First name token block
    # -------------------------------------------------
    if country and name:
        name_parts = name.split()

        if name_parts:
            first = name_parts[0]

            if len(first) >= 3:
                rows = conn.execute(
                    """
                    SELECT entity_id
                    FROM first_token_index
                    WHERE block_key = ?
                    """,
                    (country + "|" + first,)
                ).fetchall()

                candidate_ids.update(r[0] for r in rows)

    # -------------------------------------------------
    # 3. Address token blocks
    # -------------------------------------------------
    if country and address:

        tokens = address.split()
        used = set()

        for token in tokens:

            if len(token) < 5:
                continue

            if token.isdigit():
                continue

            if token in used:
                continue

            used.add(token)

            rows = conn.execute(
                """
                SELECT entity_id
                FROM address_token_index
                WHERE block_key = ?
                """,
                (country + "|" + token,)
            ).fetchall()

            candidate_ids.update(r[0] for r in rows)

            if len(used) >= 3:
                break

    # Don't return the S1 ID itself if somehow present
    candidate_ids.discard(entity_id)

    return candidate_ids


print("Candidate generation function ready.")

In [33]:
# FAST candidate generation test
# Test only ONE S1 record

row = s1_eval.iloc[0]

print("Testing:", row["entity_id"])
print("Business:", row["business_name"])
print("Country:", row["country"])

candidates = get_candidates_for_s1(row)

print("\nNumber of candidates:", len(candidates))
print("Sample candidates:", list(candidates)[:10])
print("\nDone!")

Testing: S1-708796012
Business: Board of Consumer Affairs
Country: US

Number of candidates: 53869
Sample candidates: ['S2-792816639', 'S3-428240212', 'S2-738061232', 'S3-325916292', 'S3-747842693', 'S2-331307389', 'S2-507798160', 'S3-399969514', 'S2-933687053', 'S3-410602464']

Done!

In [34]:
row = s1_eval.iloc[0]

country = normalize_text(row["country"])
name = normalize_text(row["business_name"])
address = normalize_text(row["business_address"])

print("Country:", country)
print("Name:", name)
print("Address:", address)

# -----------------------------------
# 1. NAME PREFIX
# -----------------------------------

prefix = name[:4]

prefix_count = conn.execute(
    """
    SELECT COUNT(*)
    FROM name_prefix_index
    WHERE block_key = ?
    """,
    (country + "|" + prefix,)
).fetchone()[0]

print("\nName prefix:", prefix)
print("Name-prefix candidates:", prefix_count)


# -----------------------------------
# 2. FIRST NAME TOKEN
# -----------------------------------

name_parts = name.split()

if name_parts:
    first = name_parts[0]

    first_count = conn.execute(
        """
        SELECT COUNT(*)
        FROM first_token_index
        WHERE block_key = ?
        """,
        (country + "|" + first,)
    ).fetchone()[0]

    print("\nFirst name token:", first)
    print("First-token candidates:", first_count)


# -----------------------------------
# 3. ADDRESS TOKENS
# -----------------------------------

print("\nAddress token candidates:")

for token in address.split():

    if len(token) < 5:
        continue

    if token.isdigit():
        continue

    count = conn.execute(
        """
        SELECT COUNT(*)
        FROM address_token_index
        WHERE block_key = ?
        """,
        (country + "|" + token,)
    ).fetchone()[0]

    print(f"{token}: {count}")

Country: us
Name: board of consumer affairs
Address: 122 dayton yellow springs road unit 4 fairborn oh

Name prefix: boar
Name-prefix candidates: 10215

First name token: board
First-token candidates: 9598

Address token candidates:
dayton: 18940
yellow: 2195
springs: 50283
fairborn: 2075

In [35]:
def get_candidates_for_s1(row, max_candidates=3000):
    """
    Generate controlled candidates using multiple blocking signals.

    Strategy:
    1. Collect candidates from name and address blocks.
    2. Count how many independent blocks each candidate matches.
    3. Prefer candidates matching multiple blocks.
    4. Keep at most max_candidates.
    """

    entity_id = str(row["entity_id"])
    country = normalize_text(row["country"])
    name = normalize_text(row["business_name"])
    address = normalize_text(row["business_address"])

    candidate_scores = {}

    def add_candidates(rows):
        for (candidate_id,) in rows:
            if candidate_id == entity_id:
                continue

            candidate_scores[candidate_id] = (
                candidate_scores.get(candidate_id, 0) + 1
            )

    # ------------------------------------------------
    # 1. Name prefix block
    # ------------------------------------------------

    if country and name:

        prefix = name[:4]

        if prefix:

            rows = conn.execute(
                """
                SELECT entity_id
                FROM name_prefix_index
                WHERE block_key = ?
                """,
                (country + "|" + prefix,)
            ).fetchall()

            add_candidates(rows)

    # ------------------------------------------------
    # 2. First name token block
    # ------------------------------------------------

    if country and name:

        name_parts = name.split()

        if name_parts:

            first = name_parts[0]

            if len(first) >= 3:

                rows = conn.execute(
                    """
                    SELECT entity_id
                    FROM first_token_index
                    WHERE block_key = ?
                    """,
                    (country + "|" + first,)
                ).fetchall()

                add_candidates(rows)

    # ------------------------------------------------
    # 3. Address blocks
    # ------------------------------------------------

    if country and address:

        tokens = address.split()

        used = set()

        for token in tokens:

            if len(token) < 5:
                continue

            if token.isdigit():
                continue

            if token in used:
                continue

            used.add(token)

            rows = conn.execute(
                """
                SELECT entity_id
                FROM address_token_index
                WHERE block_key = ?
                """,
                (country + "|" + token,)
            ).fetchall()

            add_candidates(rows)

            if len(used) >= 3:
                break

    # ------------------------------------------------
    # Rank candidates by number of matching blocks
    # ------------------------------------------------

    ranked_candidates = sorted(
        candidate_scores.items(),
        key=lambda x: x[1],
        reverse=True
    )

    # Keep only the strongest candidates
    ranked_candidates = ranked_candidates[:max_candidates]

    return set(
        candidate_id
        for candidate_id, score in ranked_candidates
    )


print("Updated candidate-generation function.")

Updated candidate-generation function.

In [37]:
# Test the updated candidate generator

row = s1_eval.iloc[0]

print("Testing:", row["entity_id"])
print("Business:", row["business_name"])
print("Country:", row["country"])

candidates = get_candidates_for_s1(row)

print("\nNumber of candidates:", len(candidates))
print("Sample candidates:", list(candidates)[:10])

Testing: S1-708796012
Business: Board of Consumer Affairs
Country: US

Number of candidates: 3000
Sample candidates: ['S2-45166195', 'S2-738061232', 'S2-467456381', 'S2-455976775', 'S2-249952177', 'S2-738400833', 'S2-561886678', 'S2-609797595', 'S2-908426961', 'S2-87373430']

In [38]:
# Check whether the real matches are still inside our 3,000 candidates

row = s1_eval.iloc[0]

candidates = get_candidates_for_s1(row)

# Ground-truth matches
true_matches = set()

if row["matched_entity_ids"]:
    true_matches = set(
        str(row["matched_entity_ids"]).split(",")
    )

found_matches = true_matches.intersection(candidates)
missing_matches = true_matches - candidates

print("=" * 50)
print("GROUND TRUTH CHECK")
print("=" * 50)

print("S1:", row["entity_id"])
print("Business:", row["business_name"])

print("\nTrue matches:", len(true_matches))
print("Found in candidates:", len(found_matches))
print("Missing:", len(missing_matches))

print("\nTrue matches:")
print(sorted(true_matches))

print("\nFound matches:")
print(sorted(found_matches))

print("\nMissing matches:")
print(sorted(missing_matches))

if len(true_matches) > 0:
    recall = len(found_matches) / len(true_matches)
    print("\nCandidate recall:", f"{recall:.2%}")

==================================================
GROUND TRUTH CHECK
==================================================
S1: S1-708796012
Business: Board of Consumer Affairs

True matches: 6
Found in candidates: 5
Missing: 1

True matches:
['S2-440628035', 'S2-994438467', 'S3-335174066', 'S3-338279058', 'S3-703951662', 'S3-974934575']

Found matches:
['S2-440628035', 'S2-994438467', 'S3-335174066', 'S3-338279058', 'S3-974934575']

Missing matches:
['S3-703951662']

Candidate recall: 83.33%

In [42]:
# Test a larger candidate limit

row = s1_eval.iloc[0]

candidates = get_candidates_for_s1(
    row,
    max_candidates=10000
)

true_matches = set(
    str(row["matched_entity_ids"]).split(",")
)

found_matches = true_matches.intersection(candidates)
missing_matches = true_matches - candidates

print("=" * 50)
print("10,000 CANDIDATE TEST")
print("=" * 50)

print("Total candidates:", len(candidates))
print("True matches:", len(true_matches))
print("Found:", len(found_matches))
print("Missing:", len(missing_matches))

print("\nMissing matches:")
print(sorted(missing_matches))

recall = len(found_matches) / len(true_matches)

print("\nCandidate recall:", f"{recall:.2%}")

==================================================
10,000 CANDIDATE TEST
==================================================
Total candidates: 10000
True matches: 6
Found: 6
Missing: 0

Missing matches:
[]

Candidate recall: 100.00%

In [43]:
# Candidate recall test on 100 evaluation records

TEST_SAMPLE_SIZE = 100
MAX_CANDIDATES = 10000

test_subset = s1_eval.head(TEST_SAMPLE_SIZE).copy()

candidate_counts = []
true_match_counts = []
found_true_match_counts = []

for i, (_, row) in enumerate(test_subset.iterrows(), start=1):

    candidates = get_candidates_for_s1(
        row,
        max_candidates=MAX_CANDIDATES
    )

    true_matches = set()

    if row["matched_entity_ids"]:
        true_matches = set(
            str(row["matched_entity_ids"]).split(",")
        )

    found_true = true_matches.intersection(candidates)

    candidate_counts.append(len(candidates))
    true_match_counts.append(len(true_matches))
    found_true_match_counts.append(len(found_true))

    if i % 10 == 0:
        print(f"Processed {i}/{TEST_SAMPLE_SIZE}")


total_true = sum(true_match_counts)
total_found = sum(found_true_match_counts)

recall = (
    total_found / total_true
    if total_true > 0
    else 0
)

print("\n" + "=" * 50)
print("100-RECORD CANDIDATE RECALL TEST")
print("=" * 50)

print("S1 records tested:", TEST_SAMPLE_SIZE)

print(
    "Average candidates:",
    round(np.mean(candidate_counts), 2)
)

print(
    "Minimum candidates:",
    min(candidate_counts)
)

print(
    "Maximum candidates:",
    max(candidate_counts)
)

print(
    "Average true matches:",
    round(np.mean(true_match_counts), 2)
)

print(
    "True matches found:",
    f"{total_found:,} / {total_true:,}"
)

print(
    "Candidate recall:",
    f"{recall:.2%}"
)

Processed 10/100
Processed 20/100
Processed 30/100
Processed 40/100
Processed 50/100
Processed 60/100
Processed 70/100
Processed 80/100
Processed 90/100
Processed 100/100

==================================================
100-RECORD CANDIDATE RECALL TEST
==================================================
S1 records tested: 100
Average candidates: 9331.76
Minimum candidates: 945
Maximum candidates: 10000
Average true matches: 3.65
True matches found: 320 / 365
Candidate recall: 87.67%

In [44]:
# Test improved candidate generation on the known example

row = s1_eval.iloc[0]

print("Testing:", row["entity_id"])
print("Business:", row["business_name"])
print("Country:", row["country"])

# Generate candidates
candidates = get_candidates_for_s1(
    row,
    max_candidates=10000
)

# Get ground-truth matches
true_matches = set()

if row["matched_entity_ids"]:
    true_matches = set(
        str(row["matched_entity_ids"]).split(",")
    )

# Check which true matches were retrieved
found = true_matches.intersection(candidates)
missing = true_matches - candidates

print("\n" + "=" * 50)
print("RESULT")
print("=" * 50)

print("Candidates generated:", len(candidates))
print("True matches:", len(true_matches))
print("Found:", len(found))
print("Missing:", len(missing))

print("\nTrue matches:")
print(sorted(true_matches))

print("\nFound matches:")
print(sorted(found))

print("\nMissing matches:")
print(sorted(missing))

if len(true_matches) > 0:
    recall = len(found) / len(true_matches)
else:
    recall = 0

print("\nCandidate recall:", f"{recall:.2%}")

Testing: S1-708796012
Business: Board of Consumer Affairs
Country: US

==================================================
RESULT
==================================================
Candidates generated: 10000
True matches: 6
Found: 6
Missing: 0

True matches:
['S2-440628035', 'S2-994438467', 'S3-335174066', 'S3-338279058', 'S3-703951662', 'S3-974934575']

Found matches:
['S2-440628035', 'S2-994438467', 'S3-335174066', 'S3-338279058', 'S3-703951662', 'S3-974934575']

Missing matches:
[]

Candidate recall: 100.00%

In [45]:
# Validate improved candidate generation on 100 S1 records

TEST_SAMPLE_SIZE = 100
MAX_CANDIDATES = 10000

test_subset = s1_eval.head(TEST_SAMPLE_SIZE).copy()

candidate_counts = []
true_match_counts = []
found_true_match_counts = []

for i, (_, row) in enumerate(test_subset.iterrows(), start=1):

    candidates = get_candidates_for_s1(
        row,
        max_candidates=MAX_CANDIDATES
    )

    # Ground-truth matches
    if row["matched_entity_ids"]:
        true_matches = set(
            str(row["matched_entity_ids"]).split(",")
        )
    else:
        true_matches = set()

    found_true = true_matches.intersection(candidates)

    candidate_counts.append(len(candidates))
    true_match_counts.append(len(true_matches))
    found_true_match_counts.append(len(found_true))

    if i % 10 == 0:
        print(f"Processed {i}/{TEST_SAMPLE_SIZE}")


# ---------------------------------------
# Final statistics
# ---------------------------------------

total_true = sum(true_match_counts)
total_found = sum(found_true_match_counts)

recall = (
    total_found / total_true
    if total_true > 0
    else 0
)

print("\n" + "=" * 50)
print("IMPROVED CANDIDATE RECALL TEST")
print("=" * 50)

print("S1 records tested:", TEST_SAMPLE_SIZE)

print(
    "Average candidates:",
    round(np.mean(candidate_counts), 2)
)

print(
    "Minimum candidates:",
    min(candidate_counts)
)

print(
    "Maximum candidates:",
    max(candidate_counts)
)

print(
    "Average true matches:",
    round(np.mean(true_match_counts), 2)
)

print(
    "True matches found:",
    f"{total_found:,} / {total_true:,}"
)

print(
    "Candidate recall:",
    f"{recall:.2%}"
)

Processed 10/100
Processed 20/100
Processed 30/100
Processed 40/100
Processed 50/100
Processed 60/100
Processed 70/100
Processed 80/100
Processed 90/100
Processed 100/100

==================================================
IMPROVED CANDIDATE RECALL TEST
==================================================
S1 records tested: 100
Average candidates: 9331.76
Minimum candidates: 945
Maximum candidates: 10000
Average true matches: 3.65
True matches found: 320 / 365
Candidate recall: 87.67%

In [48]:
# ============================================================
# TASK 4
# ANALYZE MISSED TRUE MATCHES
# ============================================================

def get_block_evidence(s1_row, candidate_id):
    """
    Check whether a known true match is retrievable through
    each of the existing blocking strategies.

    Returns:
        prefix_hit
        first_token_hit
        address_token_hits
        total_address_hits
    """

    country = normalize_text(s1_row["country"])
    name = normalize_text(s1_row["business_name"])
    address = normalize_text(s1_row["business_address"])

    # Get candidate record
    candidate = conn.execute(
        """
        SELECT
            entity_id,
            source,
            business_name,
            business_address,
            country,
            clean_name,
            clean_address
        FROM entities
        WHERE entity_id = ?
        """,
        (candidate_id,)
    ).fetchone()

    if candidate is None:
        return None

    (
        entity_id,
        source,
        business_name,
        business_address,
        candidate_country,
        clean_name,
        clean_address
    ) = candidate

    candidate_country_norm = normalize_text(candidate_country)

    # --------------------------------------------------------
    # Country compatibility
    # --------------------------------------------------------

    country_match = (
        country != ""
        and candidate_country_norm == country
    )

    # --------------------------------------------------------
    # 1. NAME PREFIX
    # --------------------------------------------------------

    prefix_hit = False

    if country_match and name:
        prefix = name[:4]

        if prefix:
            result = conn.execute(
                """
                SELECT 1
                FROM name_prefix_index
                WHERE block_key = ?
                AND entity_id = ?
                LIMIT 1
                """,
                (
                    country + "|" + prefix,
                    candidate_id
                )
            ).fetchone()

            prefix_hit = result is not None

    # --------------------------------------------------------
    # 2. FIRST NAME TOKEN
    # --------------------------------------------------------

    first_token_hit = False

    name_parts = name.split()

    if country_match and name_parts:

        first = name_parts[0]

        if len(first) >= 3:

            result = conn.execute(
                """
                SELECT 1
                FROM first_token_index
                WHERE block_key = ?
                AND entity_id = ?
                LIMIT 1
                """,
                (
                    country + "|" + first,
                    candidate_id
                )
            ).fetchone()

            first_token_hit = result is not None

    # --------------------------------------------------------
    # 3. ADDRESS TOKEN BLOCKS
    # --------------------------------------------------------

    address_token_hits = []

    if country_match and address:

        used = set()

        for token in address.split():

            if len(token) < 5:
                continue

            if token.isdigit():
                continue

            if token in used:
                continue

            used.add(token)

            result = conn.execute(
                """
                SELECT 1
                FROM address_token_index
                WHERE block_key = ?
                AND entity_id = ?
                LIMIT 1
                """,
                (
                    country + "|" + token,
                    candidate_id
                )
            ).fetchone()

            if result is not None:
                address_token_hits.append(token)

            if len(used) >= 3:
                break

    return {
        "candidate_id": candidate_id,
        "source": source,
        "business_name": business_name,
        "business_address": business_address,
        "country": candidate_country,
        "country_match": country_match,
        "prefix_hit": prefix_hit,
        "first_token_hit": first_token_hit,
        "address_token_hits": address_token_hits,
        "total_address_hits": len(address_token_hits)
    }

In [49]:
# ============================================================
# FIND ALL MISSED MATCHES
# ============================================================

missed_records = []

TEST_SAMPLE_SIZE = 100
MAX_CANDIDATES = 10_000

test_subset = s1_eval.head(TEST_SAMPLE_SIZE).copy()

for i, (_, row) in enumerate(test_subset.iterrows(), start=1):

    candidates = get_candidates_for_s1(
        row,
        max_candidates=MAX_CANDIDATES
    )

    true_matches = set()

    if row["matched_entity_ids"]:
        true_matches = set(
            str(row["matched_entity_ids"]).split(",")
        )

    missed = true_matches - candidates

    for missing_id in missed:

        evidence = get_block_evidence(
            row,
            missing_id
        )

        if evidence is None:
            continue

        record = {
            "s1_id": row["entity_id"],
            "s1_name": row["business_name"],
            "s1_address": row["business_address"],
            "s1_country": row["country"],
            "missing_id": missing_id,
            **evidence
        }

        missed_records.append(record)

    if i % 10 == 0:
        print(f"Analyzed {i}/{TEST_SAMPLE_SIZE}")

missed_df = pd.DataFrame(missed_records)

print("\n" + "=" * 70)
print("MISSED MATCH ANALYSIS")
print("=" * 70)

print("Total missed matches:", len(missed_df))

missed_df.head(20)

Analyzed 10/100
Analyzed 20/100
Analyzed 30/100
Analyzed 40/100
Analyzed 50/100
Analyzed 60/100
Analyzed 70/100
Analyzed 80/100
Analyzed 90/100
Analyzed 100/100

======================================================================
MISSED MATCH ANALYSIS
======================================================================
Total missed matches: 45

,s1_id,s1_name,s1_address,s1_country,missing_id,candidate_id,source,business_name,business_address,country,country_match,prefix_hit,first_token_hit,address_token_hits,total_address_hits
0,S1-387694500,Bombay Power Private Limited,"No: 32/2, 2Nd Floor, Mcc Towers, Opp To Sigma ...",India,S3-9126403,S3-9126403,S3,ಬಾಂಬೆ ಪವರ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,"No: 6-32/2, Bangalore, KA",India,True,False,False,[],0
1,S1-387694500,Bombay Power Private Limited,"No: 32/2, 2Nd Floor, Mcc Towers, Opp To Sigma ...",India,S3-904486811,S3-904486811,S3,ಬಾಂಬೆ ಪವರ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್,"2Nd Floor, Mcc Towers, Opp To Sigma Soft Tech ...",India,True,False,False,"[floor, towers, sigma]",3
2,S1-387694500,Bombay Power Private Limited,"No: 32/2, 2Nd Floor, Mcc Towers, Opp To Sigma ...",India,S3-77197957,S3-77197957,S3,Bombay Private Límited Center,,India,True,True,True,[],0
3,S1-851769617,Ear Nose & Throat Group LLC,"225 Mcalpine Drive, Fl 0, Saint Louis, MO",US,S3-385801783,S3-385801783,S3,earnosethroat.com,"225 Mcalpine Dr, Floor 0, Saint Louis, Missouri",US,True,False,False,"[mcalpine, saint]",2
4,S1-851769617,Ear Nose & Throat Group LLC,"225 Mcalpine Drive, Fl 0, Saint Louis, MO",US,S3-887912056,S3-887912056,S3,The Ear Nose & Throat Group LLC,"225 Mcalpine Dr, Fl 0, Glasgow Village, Missouri",US,True,False,False,[mcalpine],1
5,S1-254753234,Interstate Products Inc,"Houston, TX, 11923 Gatlinburg Drive",US,S3-906680755,S3-906680755,S3,Center Interstate Inc,"Gatlinburg Drive, Houston, Texas",US,True,False,False,"[houston, gatlinburg, drive]",3
6,S1-486185859,Midwest Coalition,"411 21st Street, Newton, NC",US,S3-369569928,S3-369569928,S3,Evohalo Formerly Midwest Coalition,"411 21st Street, NC, Newton",US,True,False,False,"[street, newton]",2
7,S1-886116894,XY Infoserve Private Limited,"Office No. 11, 1St Floor, Rainbow Complex, Nea...",India,S3-690261725,S3-690261725,S3,XY Infsoerve Private Limited,"Office No. 11, Jodhpur, राजस्थान",India,True,True,False,[office],1
8,S1-886116894,XY Infoserve Private Limited,"Office No. 11, 1St Floor, Rainbow Complex, Nea...",India,S2-646106704,S2-646106704,S2,PRIVATE XY INFOSERVE LIMITED,"JODHPUR, Rajasthan, 1ST FLOOR, RAINBOW COMPLEX...",India,True,False,False,[floor],1
9,S1-902552291,Varshita Food Pvt Ltd,"F-501, Park View City-2 Sector 49, Sohna Road,...",India,S2-194540012,S2-194540012,S2,Pvt Varshita Food Ltd.,"F-501, GURGAON, Haryana",India,True,False,False,[gurgaon],1
10,S1-808699530,Southern Constructions Private Limited,"Gnra 28, Gandhi Nagar Lane Kodunganoor, Vattiy...",India,S3-266930901,S3-266930901,S3,Prívate Southern Constructions Limited,"Gnra 28, Thiruvananthapuram, Trivandrum, KL",India,True,False,False,[],0
11,S1-808699530,Southern Constructions Private Limited,"Gnra 28, Gandhi Nagar Lane Kodunganoor, Vattiy...",India,S2-322687598,S2-322687598,S2,സതേൺ കൺസ്ട്രക്ഷൻസ് പ്രൈവറ്റ് ലിമിറ്റഡ്,"GNRA 28, THIRUVANANTHAPURAM, TRIVANDRUM, Kerala",India,True,False,False,[],0
12,S1-984247811,East Lakshmi Investments Private Limited,"Sf.No 259, Poyampalayam Pirivu, P.N. Road, Tir...",India,S3-7115047,S3-7115047,S3,ஈஸ்ட் லக்ஷ்மி இன்வெஸ்ட்மெண்ட்ஸ் பிரைவேட் லிமிடெட்,"Sf.no 259, Tiruppur, Coimbatore, TN",India,True,False,False,[tiruppur],1
13,S1-683192018,Gurgaon (india) Co,"Ground Floor, Tower B, Buliding No. 5, Dlf Cyb...",India,S3-896234230,S3-896234230,S3,Gurgaon Gurgaon (India),"Gurgaon, Tower B, Buliding No. 5, Dlf Cyber Ci...",India,True,True,True,[tower],1
14,S1-173339872,Classic Minerals,"17640 Maverick Drive, Natrona, WY",US,S3-48514074,S3-48514074,S3,Brixnylavera,"17640 Maverick Dr, Casper, Wyoming",US,True,False,False,[maverick],1
15,S1-545661875,Simran Investments Private Limited,"House No.3565 First Floor, Sector-23, Gurgaon,...",India,S3-656400487,S3-656400487,S3,M/s símraninvestmentsprivate.com,"House No.##3565 First Floor, Palam Vihar, Gurg...",India,True,False,False,"[house, first, floor]",3
16,S1-545661875,Simran Investments Private Limited,"House No.3565 First Floor, Sector-23, Gurgaon,...",India,S3-881558178,S3-881558178,S3,Tavolum DBA Simran Investments Private Limited,"House No.3565 First Floor, Sector-23, Gurgaon,...",India,True,False,False,"[house, first, floor]",3
17,S1-38345711,Urgent Care Physicians Inc.,"301 Stacy Weaver Drive, Fayetteville, NC",US,S3-567674608,S3-567674608,S3,Urgent Coae Physicians lnc.,"Fayetteville, North Carolina, Stacy Weaver Drive",US,True,True,True,[],0
18,S1-353226437,Sarup Merchandising Private Limited,"Building No.Vi, Ward No. 3 Kuzhur Panchayat, T...",India,S3-927260363,S3-927260363,S3,M/s Sarup Merchandising Priavte Limited,"Building No.vi, Thumbarassery, Kuzhur, KL",India,True,False,False,"[building, kuzhur]",2
19,S1-473872582,Vaa Vidyalaya Group,"Pl No 151 Aref Colony, Aurangabad, Maharashtra",India,S3-654296983,S3-654296983,S3,Sri Vaa Vidyalaya Corporation,"Pl No 0151 Arfe Colony, Aurangabad, MH",India,True,False,False,"[colony, aurangabad]",2

In [51]:
# ============================================================
# PRINT MISSED MATCH DETAILS
# ============================================================

for _, r in missed_df.iterrows():

    print("\n" + "=" * 90)

    print("S1:")
    print("ID       :", r["s1_id"])
    print("Name     :", r["s1_name"])
    print("Address  :", r["s1_address"])
    print("Country  :", r["s1_country"])

    print("\nMISSED TRUE MATCH:")
    print("ID       :", r["missing_id"])
    print("Source   :", r["source"])
    print("Name     :", r["business_name"])
    print("Address  :", r["business_address"])
    print("Country  :", r["country"])

    print("\nBLOCK EVIDENCE:")
    print("Country match :", r["country_match"])
    print("Prefix hit    :", r["prefix_hit"])
    print("First token   :", r["first_token_hit"])
    print("Address hits  :", r["address_token_hits"])

    # Generate reason
    reasons = []

    if r["country_match"]:
        reasons.append("country matched")

    if not r["prefix_hit"]:
        reasons.append("name prefix blocking failed")

    if not r["first_token_hit"]:
        reasons.append("first-token blocking failed")

    if len(r["address_token_hits"]) == 0:
        reasons.append("no address token matched")

    print("\nREASON :", "; ".join(reasons))

==========================================================================================
S1:
ID       : S1-387694500
Name     : Bombay Power Private Limited
Address  : No: 32/2, 2Nd Floor, Mcc Towers, Opp To Sigma Soft Tech Park, Whitefield Main Road, Ramagon, Danahalli, Bangalore, Karnataka
Country  : India

MISSED TRUE MATCH:
ID       : S3-9126403
Source   : S3
Name     : ಬಾಂಬೆ ಪವರ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
Address  : No: 6-32/2, Bangalore, KA
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : []

REASON : country matched; name prefix blocking failed; first-token blocking failed; no address token matched

==========================================================================================
S1:
ID       : S1-387694500
Name     : Bombay Power Private Limited
Address  : No: 32/2, 2Nd Floor, Mcc Towers, Opp To Sigma Soft Tech Park, Whitefield Main Road, Ramagon, Danahalli, Bangalore, Karnataka
Country  : India

MISSED TRUE MATCH:
ID       : S3-904486811
Source   : S3
Name     : ಬಾಂಬೆ ಪವರ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
Address  : 2Nd Floor, Mcc Towers, Opp To Sigma Soft Tech Park, Whitefield Main Road, Ramagon, Danahalli, No: 6-32/2, Bangalore, KA
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['floor', 'towers', 'sigma']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-387694500
Name     : Bombay Power Private Limited
Address  : No: 32/2, 2Nd Floor, Mcc Towers, Opp To Sigma Soft Tech Park, Whitefield Main Road, Ramagon, Danahalli, Bangalore, Karnataka
Country  : India

MISSED TRUE MATCH:
ID       : S3-77197957
Source   : S3
Name     : Bombay Private Límited Center
Address  :
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : True
First token   : True
Address hits  : []

REASON : country matched; no address token matched

==========================================================================================
S1:
ID       : S1-851769617
Name     : Ear Nose & Throat Group LLC
Address  : 225 Mcalpine Drive, Fl 0, Saint Louis, MO
Country  : US

MISSED TRUE MATCH:
ID       : S3-385801783
Source   : S3
Name     : earnosethroat.com
Address  : 225 Mcalpine Dr, Floor 0, Saint Louis, Missouri
Country  : US

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['mcalpine', 'saint']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-851769617
Name     : Ear Nose & Throat Group LLC
Address  : 225 Mcalpine Drive, Fl 0, Saint Louis, MO
Country  : US

MISSED TRUE MATCH:
ID       : S3-887912056
Source   : S3
Name     : The Ear Nose & Throat Group LLC
Address  : 225 Mcalpine Dr, Fl 0, Glasgow Village, Missouri
Country  : US

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['mcalpine']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-254753234
Name     : Interstate Products Inc
Address  : Houston, TX, 11923 Gatlinburg Drive
Country  : US

MISSED TRUE MATCH:
ID       : S3-906680755
Source   : S3
Name     : Center Interstate Inc
Address  : Gatlinburg Drive, Houston, Texas
Country  : US

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['houston', 'gatlinburg', 'drive']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-486185859
Name     : Midwest Coalition
Address  : 411 21st Street, Newton, NC
Country  : US

MISSED TRUE MATCH:
ID       : S3-369569928
Source   : S3
Name     : Evohalo Formerly Midwest Coalition
Address  : 411 21st Street, NC, Newton
Country  : US

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['street', 'newton']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-886116894
Name     : XY Infoserve Private Limited
Address  : Office No. 11, 1St Floor, Rainbow Complex, Near Under Bridge Paota C Road, Jodhpur, Rajasthan
Country  : India

MISSED TRUE MATCH:
ID       : S3-690261725
Source   : S3
Name     : XY Infsoerve  Private Limited
Address  : Office No. 11, Jodhpur, राजस्थान
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : True
First token   : False
Address hits  : ['office']

REASON : country matched; first-token blocking failed

==========================================================================================
S1:
ID       : S1-886116894
Name     : XY Infoserve Private Limited
Address  : Office No. 11, 1St Floor, Rainbow Complex, Near Under Bridge Paota C Road, Jodhpur, Rajasthan
Country  : India

MISSED TRUE MATCH:
ID       : S2-646106704
Source   : S2
Name     : PRIVATE XY INFOSERVE LIMITED
Address  : JODHPUR, Rajasthan, 1ST FLOOR, RAINBOW COMPLEX, NEAR UNDER BRIDGE PAOTA C ROAD, OFFICE NO. 81
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['floor']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-902552291
Name     : Varshita Food Pvt Ltd
Address  : F-501, Park View City-2 Sector 49, Sohna Road, Gurgaon, Haryana
Country  : India

MISSED TRUE MATCH:
ID       : S2-194540012
Source   : S2
Name     : Pvt Varshita Food Ltd.
Address  : F-501, GURGAON, Haryana
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['gurgaon']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-808699530
Name     : Southern Constructions Private Limited
Address  : Gnra 28, Gandhi Nagar Lane Kodunganoor, Vattiyoorkavu, Thiruvananthapuram, Trivandrum, Kerala
Country  : India

MISSED TRUE MATCH:
ID       : S3-266930901
Source   : S3
Name     : Prívate Southern Constructions Limited
Address  : Gnra 28, Thiruvananthapuram, Trivandrum, KL
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : []

REASON : country matched; name prefix blocking failed; first-token blocking failed; no address token matched

==========================================================================================
S1:
ID       : S1-808699530
Name     : Southern Constructions Private Limited
Address  : Gnra 28, Gandhi Nagar Lane Kodunganoor, Vattiyoorkavu, Thiruvananthapuram, Trivandrum, Kerala
Country  : India

MISSED TRUE MATCH:
ID       : S2-322687598
Source   : S2
Name     : സതേൺ കൺസ്ട്രക്ഷൻസ് പ്രൈവറ്റ് ലിമിറ്റഡ്
Address  : GNRA 28, THIRUVANANTHAPURAM, TRIVANDRUM, Kerala
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : []

REASON : country matched; name prefix blocking failed; first-token blocking failed; no address token matched

==========================================================================================
S1:
ID       : S1-984247811
Name     : East Lakshmi Investments Private Limited
Address  : Sf.No 259, Poyampalayam Pirivu, P.N. Road, Tiruppur, Coimbatore, Tamil Nadu
Country  : India

MISSED TRUE MATCH:
ID       : S3-7115047
Source   : S3
Name     : ஈஸ்ட் லக்ஷ்மி இன்வெஸ்ட்மெண்ட்ஸ் பிரைவேட் லிமிடெட்
Address  : Sf.no 259, Tiruppur, Coimbatore, TN
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['tiruppur']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-683192018
Name     : Gurgaon (india) Co
Address  : Ground Floor, Tower B, Buliding No. 5, Dlf Cyber City Phase Iii, Gurgaon, Haryana
Country  : India

MISSED TRUE MATCH:
ID       : S3-896234230
Source   : S3
Name     : Gurgaon Gurgaon (India)
Address  : Gurgaon, Tower B, Buliding No. 5, Dlf Cyber City Phase Iii, हरियाणा, Ground Floor
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : True
First token   : True
Address hits  : ['tower']

REASON : country matched

==========================================================================================
S1:
ID       : S1-173339872
Name     : Classic Minerals
Address  : 17640 Maverick Drive, Natrona, WY
Country  : US

MISSED TRUE MATCH:
ID       : S3-48514074
Source   : S3
Name     : Brixnylavera
Address  : 17640 Maverick Dr, Casper, Wyoming
Country  : US

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['maverick']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-545661875
Name     : Simran Investments Private Limited
Address  : House No.3565 First Floor, Sector-23, Gurgaon, Palam Vihar, Gurgaon, Haryana
Country  : India

MISSED TRUE MATCH:
ID       : S3-656400487
Source   : S3
Name     : M/s símraninvestmentsprivate.com
Address  : House No.##3565 First Floor, Palam Vihar, Gurgaon, हरियाणा
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['house', 'first', 'floor']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-545661875
Name     : Simran Investments Private Limited
Address  : House No.3565 First Floor, Sector-23, Gurgaon, Palam Vihar, Gurgaon, Haryana
Country  : India

MISSED TRUE MATCH:
ID       : S3-881558178
Source   : S3
Name     : Tavolum DBA Simran Investments Private Limited
Address  : House No.3565 First Floor, Sector-23, Gurgaon, Palam Vihar, Gurgaon, Haryana
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['house', 'first', 'floor']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-38345711
Name     : Urgent Care Physicians Inc.
Address  : 301 Stacy Weaver Drive, Fayetteville, NC
Country  : US

MISSED TRUE MATCH:
ID       : S3-567674608
Source   : S3
Name     : Urgent Coae Physicians lnc.
Address  : Fayetteville, North Carolina, Stacy Weaver Drive
Country  : US

BLOCK EVIDENCE:
Country match : True
Prefix hit    : True
First token   : True
Address hits  : []

REASON : country matched; no address token matched

==========================================================================================
S1:
ID       : S1-353226437
Name     : Sarup Merchandising Private Limited
Address  : Building No.Vi, Ward No. 3 Kuzhur Panchayat, Thumbarassery, Kuzhur, Kerala
Country  : India

MISSED TRUE MATCH:
ID       : S3-927260363
Source   : S3
Name     : M/s Sarup Merchandising Priavte Limited
Address  : Building No.vi, Thumbarassery, Kuzhur, KL
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['building', 'kuzhur']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-473872582
Name     : Vaa Vidyalaya Group
Address  : Pl No 151 Aref Colony, Aurangabad, Maharashtra
Country  : India

MISSED TRUE MATCH:
ID       : S3-654296983
Source   : S3
Name     : Sri Vaa  Vidyalaya Corporation
Address  : Pl No 0151 Arfe Colony, Aurangabad, MH
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['colony', 'aurangabad']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-473872582
Name     : Vaa Vidyalaya Group
Address  : Pl No 151 Aref Colony, Aurangabad, Maharashtra
Country  : India

MISSED TRUE MATCH:
ID       : S3-146161403
Source   : S3
Name     : Dr Vaa Vaa Group Vidyalaya
Address  : Pl No 0151 Aref Colony, Aurangabad, MH
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['colony', 'aurangabad']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-404137176
Name     : American Choice Dental LLC
Address  : 64 Wydendown Road, New Canaan, CT
Country  : US

MISSED TRUE MATCH:
ID       : S3-552512972
Source   : S3
Name     : LLC American Choice Detcl
Address  : 64 Wydendown Road, New Canaan, Connecticut
Country  : US

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['wydendown', 'canaan']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-944519934
Name     : PF Institute Ltd
Address  : House No 260C Bock Qu Landmark Pitampura, New Delhi, East Delhi, Delhi
Country  : India

MISSED TRUE MATCH:
ID       : S3-890735110
Source   : S3
Name     : PF  lnstitute
Address  : New Delhi, East Delhi, Plot 233 House No 260C Bock Qu Landmark Pitampura, DL
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['house', 'landmark']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-936095007
Name     : Kashyap Infratech Bangalore
Address  : 201, Diamond Nest, Nr Colony, Old Airport Road, Konanaagrahara, Bangalore, Karnataka
Country  : India

MISSED TRUE MATCH:
ID       : S3-861025184
Source   : S3
Name     : Mr Kashyap-Bangalore Center
Address  : 201, Bangalore, KA
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : []

REASON : country matched; name prefix blocking failed; first-token blocking failed; no address token matched

==========================================================================================
S1:
ID       : S1-629879582
Name     : New White Investment Private Limited
Address  : C/O Sajid Ansari, 237 Green Park Society Opp I D Chauhan, Talala Road, Patan, Junagadh - Veraval, Junagadh, Gujarat
Country  : India

MISSED TRUE MATCH:
ID       : S3-984126700
Source   : S3
Name     : ન્યૂ વ્હાઇટ ઇન્વેસ્ટમેન્ટ પ્રાઇવેટ લિમિટેડ
Address  : C/o Sajid Ansari, <NULL>, Junagadh, Junagadh - Veraval, GJ
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['sajid', 'ansari']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-629879582
Name     : New White Investment Private Limited
Address  : C/O Sajid Ansari, 237 Green Park Society Opp I D Chauhan, Talala Road, Patan, Junagadh - Veraval, Junagadh, Gujarat
Country  : India

MISSED TRUE MATCH:
ID       : S3-78216650
Source   : S3
Name     : Dovadrex DBA New White Investment Private Limited
Address  : C/O Sajid Ansari, 237 Green Park Society Opp I D Chauhan, Talala Road, Patan, Junagadh - Veraval, Junagadh, Gujarat
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['sajid', 'ansari', 'green']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-629879582
Name     : New White Investment Private Limited
Address  : C/O Sajid Ansari, 237 Green Park Society Opp I D Chauhan, Talala Road, Patan, Junagadh - Veraval, Junagadh, Gujarat
Country  : India

MISSED TRUE MATCH:
ID       : S2-821445856
Source   : S2
Name     : ન્યૂ વ્હાઇટ ઇન્વેસ્ટમેન્ટ પ્રાઇવેટ લિમિટેડ
Address  : C/O SJID ANSARI, 237 GREEN PARK SOCIETY OPP I D CHAUHAN, TALALA ROAD, PATAN, JUNAGADH - VERAVAL, JUNAGADH, ગુજરાત
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['ansari', 'green']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-629879582
Name     : New White Investment Private Limited
Address  : C/O Sajid Ansari, 237 Green Park Society Opp I D Chauhan, Talala Road, Patan, Junagadh - Veraval, Junagadh, Gujarat
Country  : India

MISSED TRUE MATCH:
ID       : S3-214386532
Source   : S3
Name     : ન્યૂ વ્હાઇટ ઇન્વેસ્ટમેન્ટ પ્રાઇવેટ લિમિટેડ
Address  : C/o Sajid Ansari, <NULL>, Junagadh - Veraval, Junagadh, ગુજરાત
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['sajid', 'ansari']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-629879582
Name     : New White Investment Private Limited
Address  : C/O Sajid Ansari, 237 Green Park Society Opp I D Chauhan, Talala Road, Patan, Junagadh - Veraval, Junagadh, Gujarat
Country  : India

MISSED TRUE MATCH:
ID       : S3-727508088
Source   : S3
Name     : Private New White Investment Limited
Address  : C/o Sajid Ansari, <NULL>, Junagadh - Veraval, Junagadh, GJ
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : ['sajid', 'ansari']

REASON : country matched; name prefix blocking failed; first-token blocking failed

==========================================================================================
S1:
ID       : S1-629879582
Name     : New White Investment Private Limited
Address  : C/O Sajid Ansari, 237 Green Park Society Opp I D Chauhan, Talala Road, Patan, Junagadh - Veraval, Junagadh, Gujarat
Country  : India

MISSED TRUE MATCH:
ID       : S2-535171264
Source   : S2
Name     : ન્યૂ વ્હાઇટ ઇન્વેસ્ટમેન્ટ પ્રાઇવેટ લિમિટેડ
Address  : JUNAGADH - VERAVAL, Gujarat, JUNAGADH, C/O SJAID ANSARI, 237 GREEN PARK SOCIETY OPP I D CHAUHAN, TALALA ROAD, PATAN
Country  : India

BLOCK EVIDENCE:
Country match : True
Prefix hit    : False
First token   : False
Address hits  : []

REASON : country matched; name prefix blocking failed; first-token blocking failed; no address token matched

==========================================================================================
S1:
ID       : S1-629879582
Name     : New White Investment Private Limited
Address  : C/O Sajid Ansari, 237 Green Park Society Opp I D Chauhan, Talala Road, Patan, Junagadh - Veraval, Junagadh, Gujarat
Country  : India

MISSED TRUE MATCH:
ID       : S3-117318892
Source   : S3
Name     : ન્યૂ વ્હાઇટ ઇન્વેસ્ટમેન્ટ Private Limited
Address  : C/o Sajid Ansari, <NULL>, GJ, Junagadh - Veraval, Junagadh

In [65]:
# ============================================================
# GET FULL CANDIDATE RANKING
# ============================================================

def get_ranked_candidates_full(row):
    """
    Same blocking logic as the existing generator,
    but DOES NOT truncate to 10,000.
    """

    entity_id = str(row["entity_id"])

    country = normalize_text(row["country"])
    name = normalize_text(row["business_name"])
    address = normalize_text(row["business_address"])

    candidate_scores = {}

    def add_candidates(rows):
        for (candidate_id,) in rows:

            if candidate_id == entity_id:
                continue

            candidate_scores[candidate_id] = (
                candidate_scores.get(candidate_id, 0) + 1
            )

    # --------------------------------------------------------
    # NAME PREFIX
    # --------------------------------------------------------

    if country and name:

        prefix = name[:4]

        if prefix:

            rows = conn.execute(
                """
                SELECT entity_id
                FROM name_prefix_index
                WHERE block_key = ?
                """,
                (country + "|" + prefix,)
            ).fetchall()

            add_candidates(rows)

    # --------------------------------------------------------
    # FIRST TOKEN
    # --------------------------------------------------------

    if country and name:

        parts = name.split()

        if parts:

            first = parts[0]

            if len(first) >= 3:

                rows = conn.execute(
                    """
                    SELECT entity_id
                    FROM first_token_index
                    WHERE block_key = ?
                    """,
                    (country + "|" + first,)
                ).fetchall()

                add_candidates(rows)

    # --------------------------------------------------------
    # ADDRESS TOKENS
    # --------------------------------------------------------

    if country and address:

        used = set()

        for token in address.split():

            if len(token) < 5:
                continue

            if token.isdigit():
                continue

            if token in used:
                continue

            used.add(token)

            rows = conn.execute(
                """
                SELECT entity_id
                FROM address_token_index
                WHERE block_key = ?
                """,
                (country + "|" + token,)
            ).fetchall()

            add_candidates(rows)

            if len(used) >= 3:
                break

    return sorted(
        candidate_scores.items(),
        key=lambda x: x[1],
        reverse=True
    )

In [66]:
# ============================================================
# FAST VERSION — CHECK THE 45 MISSED MATCHES
# ============================================================

def check_single_match_blocks(row, true_id):

    country = normalize_text(row["country"])
    name = normalize_text(row["business_name"])
    address = normalize_text(row["business_address"])

    result = {
        "s1_id": row["entity_id"],
        "true_id": true_id,
        "prefix_hit": False,
        "first_token_hit": False,
        "address_hits": [],
    }

    # --------------------------------------------------------
    # 1. NAME PREFIX
    # --------------------------------------------------------

    if country and name:

        prefix = name[:4]

        if prefix:

            block_key = country + "|" + prefix

            hit = conn.execute(
                """
                SELECT 1
                FROM name_prefix_index
                WHERE block_key = ?
                  AND entity_id = ?
                LIMIT 1
                """,
                (block_key, true_id)
            ).fetchone()

            result["prefix_hit"] = hit is not None

    # --------------------------------------------------------
    # 2. FIRST TOKEN
    # --------------------------------------------------------

    if country and name:

        parts = name.split()

        if parts:

            first = parts[0]

            if len(first) >= 3:

                block_key = country + "|" + first

                hit = conn.execute(
                    """
                    SELECT 1
                    FROM first_token_index
                    WHERE block_key = ?
                      AND entity_id = ?
                    LIMIT 1
                    """,
                    (block_key, true_id)
                ).fetchone()

                result["first_token_hit"] = hit is not None

    # --------------------------------------------------------
    # 3. ADDRESS TOKENS
    # --------------------------------------------------------

    if country and address:

        used = set()

        for token in address.split():

            if len(token) < 5:
                continue

            if token.isdigit():
                continue

            if token in used:
                continue

            used.add(token)

            block_key = country + "|" + token

            hit = conn.execute(
                """
                SELECT 1
                FROM address_token_index
                WHERE block_key = ?
                  AND entity_id = ?
                LIMIT 1
                """,
                (block_key, true_id)
            ).fetchone()

            if hit is not None:
                result["address_hits"].append(token)

            if len(used) >= 3:
                break

    # --------------------------------------------------------
    # CLASSIFY
    # --------------------------------------------------------

    if (
        result["prefix_hit"]
        or result["first_token_hit"]
        or len(result["address_hits"]) > 0
    ):
        result["reason"] = "BLOCK_FOUND_BUT_RANKED_OUT"
    else:
        result["reason"] = "NO_EXISTING_BLOCK_HIT"

    return result

In [67]:
# ============================================================
# FAST TASK 4 ANALYSIS
# Uses the already-created missed_df
# ============================================================

print("Starting Task 4 analysis...", flush=True)

fast_analysis = []

total = len(missed_df)

print(f"Missed matches to analyze: {total}", flush=True)

for idx, (_, r) in enumerate(missed_df.iterrows(), start=1):

    # Find original S1 row
    original_row = test_subset[
        test_subset["entity_id"].astype(str)
        == str(r["s1_id"])
    ]

    if original_row.empty:
        continue

    row = original_row.iloc[0]

    result = check_single_match_blocks(
        row,
        str(r["missing_id"])
    )

    fast_analysis.append(result)

    # Progress every 5 records
    if idx % 5 == 0 or idx == total:
        print(
            f"Analyzed {idx}/{total} missed matches...",
            flush=True
        )

fast_analysis_df = pd.DataFrame(fast_analysis)

print("\n" + "=" * 70)
print("TASK 4 COMPLETE")
print("=" * 70)

print(
    fast_analysis_df["reason"].value_counts()
)

fast_analysis_df.head(20)

Starting Task 4 analysis...
Missed matches to analyze: 45
Analyzed 5/45 missed matches...
Analyzed 10/45 missed matches...
Analyzed 15/45 missed matches...
Analyzed 20/45 missed matches...
Analyzed 25/45 missed matches...
Analyzed 30/45 missed matches...
Analyzed 35/45 missed matches...
Analyzed 40/45 missed matches...
Analyzed 45/45 missed matches...

======================================================================
TASK 4 COMPLETE
======================================================================
reason
BLOCK_FOUND_BUT_RANKED_OUT    37
NO_EXISTING_BLOCK_HIT          8
Name: count, dtype: int64

,s1_id,true_id,prefix_hit,first_token_hit,address_hits,reason
0,S1-387694500,S3-9126403,False,False,[],NO_EXISTING_BLOCK_HIT
1,S1-387694500,S3-904486811,False,False,"[floor, towers, sigma]",BLOCK_FOUND_BUT_RANKED_OUT
2,S1-387694500,S3-77197957,True,True,[],BLOCK_FOUND_BUT_RANKED_OUT
3,S1-851769617,S3-385801783,False,False,"[mcalpine, saint]",BLOCK_FOUND_BUT_RANKED_OUT
4,S1-851769617,S3-887912056,False,False,[mcalpine],BLOCK_FOUND_BUT_RANKED_OUT
5,S1-254753234,S3-906680755,False,False,"[houston, gatlinburg, drive]",BLOCK_FOUND_BUT_RANKED_OUT
6,S1-486185859,S3-369569928,False,False,"[street, newton]",BLOCK_FOUND_BUT_RANKED_OUT
7,S1-886116894,S3-690261725,True,False,[office],BLOCK_FOUND_BUT_RANKED_OUT
8,S1-886116894,S2-646106704,False,False,[floor],BLOCK_FOUND_BUT_RANKED_OUT
9,S1-902552291,S2-194540012,False,False,[gurgaon],BLOCK_FOUND_BUT_RANKED_OUT
10,S1-808699530,S3-266930901,False,False,[],NO_EXISTING_BLOCK_HIT
11,S1-808699530,S2-322687598,False,False,[],NO_EXISTING_BLOCK_HIT
12,S1-984247811,S3-7115047,False,False,[tiruppur],BLOCK_FOUND_BUT_RANKED_OUT
13,S1-683192018,S3-896234230,True,True,[tower],BLOCK_FOUND_BUT_RANKED_OUT
14,S1-173339872,S3-48514074,False,False,[maverick],BLOCK_FOUND_BUT_RANKED_OUT
15,S1-545661875,S3-656400487,False,False,"[house, first, floor]",BLOCK_FOUND_BUT_RANKED_OUT
16,S1-545661875,S3-881558178,False,False,"[house, first, floor]",BLOCK_FOUND_BUT_RANKED_OUT
17,S1-38345711,S3-567674608,True,True,[],BLOCK_FOUND_BUT_RANKED_OUT
18,S1-353226437,S3-927260363,False,False,"[building, kuzhur]",BLOCK_FOUND_BUT_RANKED_OUT
19,S1-473872582,S3-654296983,False,False,"[colony, aurangabad]",BLOCK_FOUND_BUT_RANKED_OUT

In [63]:
print(len(missed_df))
print(missed_df.head())

45
          s1_id                       s1_name  \
0  S1-387694500  Bombay Power Private Limited
1  S1-387694500  Bombay Power Private Limited
2  S1-387694500  Bombay Power Private Limited
3  S1-851769617   Ear Nose & Throat Group LLC
4  S1-851769617   Ear Nose & Throat Group LLC

                                          s1_address s1_country    missing_id  \
0  No: 32/2, 2Nd Floor, Mcc Towers, Opp To Sigma ...      India    S3-9126403
1  No: 32/2, 2Nd Floor, Mcc Towers, Opp To Sigma ...      India  S3-904486811
2  No: 32/2, 2Nd Floor, Mcc Towers, Opp To Sigma ...      India   S3-77197957
3          225 Mcalpine Drive, Fl 0, Saint Louis, MO         US  S3-385801783
4          225 Mcalpine Drive, Fl 0, Saint Louis, MO         US  S3-887912056

   candidate_id source                    business_name  \
0    S3-9126403     S3     ಬಾಂಬೆ ಪವರ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
1  S3-904486811     S3     ಬಾಂಬೆ ಪವರ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
2   S3-77197957     S3    Bombay Private Límited Center
3  S3-385801783     S3                earnosethroat.com
4  S3-887912056     S3  The Ear Nose & Throat Group LLC

                                    business_address country  country_match  \
0                          No: 6-32/2, Bangalore, KA   India           True
1  2Nd Floor, Mcc Towers, Opp To Sigma Soft Tech ...   India           True
2                                                      India           True
3    225 Mcalpine Dr, Floor 0, Saint Louis, Missouri      US           True
4   225 Mcalpine Dr, Fl 0, Glasgow Village, Missouri      US           True

   prefix_hit  first_token_hit      address_token_hits  total_address_hits
0       False            False                      []                   0
1       False            False  [floor, towers, sigma]                   3
2        True             True                      []                   0
3       False            False       [mcalpine, saint]                   2
4       False            False              [mcalpine]                   1

In [68]:
# ============================================================
# TASK 5 VALIDATION
# TEST WEIGHTED CANDIDATE GENERATION ON 100 S1 RECORDS
# ============================================================

TEST_SAMPLE_SIZE = 100
MAX_CANDIDATES = 10000

test_subset = s1_eval.head(TEST_SAMPLE_SIZE).copy()

candidate_counts = []
true_match_counts = []
found_true_match_counts = []

for i, (_, row) in enumerate(
    test_subset.iterrows(),
    start=1
):

    candidates = get_candidates_for_s1(
        row,
        max_candidates=MAX_CANDIDATES
    )

    # --------------------------------------------------------
    # Ground-truth matches
    # --------------------------------------------------------

    if row["matched_entity_ids"]:

        true_matches = set(
            str(row["matched_entity_ids"]).split(",")
        )

    else:

        true_matches = set()

    # --------------------------------------------------------
    # Check retrieved true matches
    # --------------------------------------------------------

    found_true = true_matches.intersection(candidates)

    candidate_counts.append(
        len(candidates)
    )

    true_match_counts.append(
        len(true_matches)
    )

    found_true_match_counts.append(
        len(found_true)
    )

    if i % 10 == 0:

        print(
            f"Processed {i}/{TEST_SAMPLE_SIZE}"
        )

# ============================================================
# FINAL STATISTICS
# ============================================================

total_true = sum(true_match_counts)

total_found = sum(
    found_true_match_counts
)

recall = (
    total_found / total_true
    if total_true > 0
    else 0
)

print("\n" + "=" * 60)
print("TASK 5 — WEIGHTED CANDIDATE RECALL TEST")
print("=" * 60)

print(
    "S1 records tested:",
    TEST_SAMPLE_SIZE
)

print(
    "Average candidates:",
    round(np.mean(candidate_counts), 2)
)

print(
    "Minimum candidates:",
    min(candidate_counts)
)

print(
    "Maximum candidates:",
    max(candidate_counts)
)

print(
    "Average true matches:",
    round(np.mean(true_match_counts), 2)
)

print(
    "True matches found:",
    f"{total_found:,} / {total_true:,}"
)  

print(
    "Candidate recall:",
    f"{recall:.2%}"
)

Processed 10/100
Processed 20/100
Processed 30/100
Processed 40/100
Processed 50/100
Processed 60/100
Processed 70/100
Processed 80/100
Processed 90/100
Processed 100/100

============================================================
TASK 5 — WEIGHTED CANDIDATE RECALL TEST
============================================================
S1 records tested: 100
Average candidates: 9331.76
Minimum candidates: 945
Maximum candidates: 10000
Average true matches: 3.65
True matches found: 320 / 365
Candidate recall: 87.67%

In [69]:
# ============================================================
# TASK 5 VALIDATION
# TEST WEIGHTED CANDIDATE GENERATION ON 100 S1 RECORDS
# ============================================================

TEST_SAMPLE_SIZE = 100
MAX_CANDIDATES = 10000

test_subset = s1_eval.head(TEST_SAMPLE_SIZE).copy()

candidate_counts = []
true_match_counts = []
found_true_match_counts = []

for i, (_, row) in enumerate(
    test_subset.iterrows(),
    start=1
):

    candidates = get_candidates_for_s1(
        row,
        max_candidates=MAX_CANDIDATES
    )

    # --------------------------------------------------------
    # Ground-truth matches
    # --------------------------------------------------------

    if row["matched_entity_ids"]:

        true_matches = set(
            str(row["matched_entity_ids"]).split(",")
        )

    else:

        true_matches = set()

    # --------------------------------------------------------
    # Check retrieved true matches
    # --------------------------------------------------------

    found_true = true_matches.intersection(candidates)

    candidate_counts.append(
        len(candidates)
    )

    true_match_counts.append(
        len(true_matches)
    )

    found_true_match_counts.append(
        len(found_true)
    )

    if i % 10 == 0:

        print(
            f"Processed {i}/{TEST_SAMPLE_SIZE}"
        )

# ============================================================
# FINAL STATISTICS
# ============================================================

total_true = sum(true_match_counts)

total_found = sum(
    found_true_match_counts
)

recall = (
    total_found / total_true
    if total_true > 0
    else 0
)

print("\n" + "=" * 60)
print("TASK 5 — WEIGHTED CANDIDATE RECALL TEST")
print("=" * 60)

print(
    "S1 records tested:",
    TEST_SAMPLE_SIZE
)

print(
    "Average candidates:",
    round(np.mean(candidate_counts), 2)
)

print(
    "Minimum candidates:",
    min(candidate_counts)
)

print(
    "Maximum candidates:",
    max(candidate_counts)
)

print(
    "Average true matches:",
    round(np.mean(true_match_counts), 2)
)

print(
    "True matches found:",
    f"{total_found:,} / {total_true:,}"
)

print(
    "Candidate recall:",
    f"{recall:.2%}"
)

Processed 10/100
Processed 20/100
Processed 30/100
Processed 40/100
Processed 50/100
Processed 60/100
Processed 70/100
Processed 80/100
Processed 90/100
Processed 100/100

============================================================
TASK 5 — WEIGHTED CANDIDATE RECALL TEST
============================================================
S1 records tested: 100
Average candidates: 9331.76
Minimum candidates: 945
Maximum candidates: 10000
Average true matches: 3.65
True matches found: 320 / 365
Candidate recall: 87.67%

In [89]:
# ============================================================
# STEP 6: TEST CANDIDATE RECALL AGAIN
# ============================================================
"""
Run the same 100-record test again.
Compare recall improvement from Task 5.

Before: 320 / 365 = 87.67%
After:  ??? / 365 = ???%
"""

import pandas as pd
import sqlite3

def test_candidate_recall_step6(
    s1_eval,
    ground_truth,
    get_candidates_func,
    num_test_records=100,
    verbose=True
):
    """
    Test candidate generation on 100 S1 records.
    Compare against baseline 87.67%.
    
    Returns:
        dict with recall metrics
    """
    
    test_s1_ids = s1_eval['entity_id'].head(num_test_records).tolist()
    
    total_true_matches = 0
    total_found_matches = 0
    missed_matches = []
    candidate_counts = []
    recall_by_s1 = {}
    
    print("\n" + "="*70)
    print("STEP 6: TEST CANDIDATE RECALL")
    print("="*70)
    print(f"\nTesting {num_test_records} S1 records...\n")
    
    for idx, s1_id in enumerate(test_s1_ids, 1):
        
        # Get ground truth for this S1
        gt_for_s1 = ground_truth[
            ground_truth['source1_entity_id'] == s1_id
        ]
        
        # True matches from S2 and S3
        true_s2 = set(gt_for_s1['source2_entity_id'].dropna().unique())
        true_s3 = set(gt_for_s1['source3_entity_id'].dropna().unique())
        true_matches = true_s2 | true_s3

In [77]:
# ============================================================
# FIX: INSTALL RAPIDFUZZ
# ============================================================

%pip install rapidfuzz

Collecting rapidfuzz
  Using cached rapidfuzz-3.14.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Using cached rapidfuzz-3.14.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.6
Note: you may need to restart the kernel to use updated packages.

In [78]:
from rapidfuzz import fuzz

print("RapidFuzz is working!")

RapidFuzz is working!

In [80]:
# ============================================================
# CHECK STEP 6 STATUS
# ============================================================

print("step6_results exists:",
      'step6_results' in globals())

print("get_candidates_for_s1_v3 exists:",
      'get_candidates_for_s1_v3' in globals())

print("s1_eval exists:",
      's1_eval' in globals())

print("ground_truth exists:",
      'ground_truth' in globals())

print("conn exists:",
      'conn' in globals())

step6_results exists: False
get_candidates_for_s1_v3 exists: False
s1_eval exists: True
ground_truth exists: False
conn exists: True

In [83]:
# ============================================================
# CHECK AVAILABLE VARIABLES
# ============================================================

print("Available relevant variables:")

for name in sorted(globals()):
    if any(x in name.lower() for x in [
        "ground",
        "truth",
        "match",
        "s1",
        "s2",
        "s3"
    ]):
        print(" -", name)

Available relevant variables:
 - S1_SAMPLE_SIZE
 - SequenceMatcher
 - TRAIN_S1_LIMIT
 - check_single_match_blocks
 - found_matches
 - found_true_match_counts
 - get_candidates_for_s1
 - ground_truth_sample
 - matches
 - missing_matches
 - s1_eval
 - s1_eval_parts
 - s1_sample
 - true_match_counts
 - true_matches

In [84]:
# ============================================================
# CHECK SQLITE TABLES
# ============================================================

tables = conn.execute("""
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name
""").fetchall()

print("SQLite tables:")

for table in tables:
    print(" -", table[0])

SQLite tables:
 - address_token_index
 - entities
 - first_token_index
 - name_prefix_index

In [85]:
# ============================================================
# STEP 6 RECOVERY - CHECK GROUND TRUTH SAMPLE
# ============================================================

print("ground_truth_sample type:",
      type(ground_truth_sample))

print("Shape:",
      ground_truth_sample.shape)

print("\nColumns:")
print(ground_truth_sample.columns.tolist())

display(
    ground_truth_sample.head()
)

ground_truth_sample type: <class 'pandas.core.frame.DataFrame'>
Shape: (20000, 2)

Columns:
['source1_entity_id', 'matched_entity_ids']

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [98]:
# ============================================================
# RESTORE GROUND TRUTH FROM EXISTING DATA
# ============================================================

ground_truth = ground_truth_sample.copy()

print("ground_truth restored successfully.")
print("Shape:", ground_truth.shape)
print("Columns:", ground_truth.columns.tolist())

display(ground_truth.head())

ground_truth restored successfully.
Shape: (20000, 2)
Columns: ['source1_entity_id', 'matched_entity_ids']

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [99]:
print('get_candidates_for_s1_v3' in globals())

False

In [100]:
# ============================================================
# TASK 5 - V3 IMPROVED CANDIDATE GENERATOR
# ============================================================

def get_candidates_for_s1_v3(
    row,
    max_candidates=20_000
):
    """
    Improved candidate generation using:
      1. Name prefix
      2. Multiple name tokens
      3. Address tokens
      4. Multi-signal ranking

    Returns:
        Set of candidate entity IDs
    """

    entity_id = str(row["entity_id"])

    country = normalize_text(
        row.get("country", "")
    )

    name = normalize_text(
        row.get("business_name", "")
    )

    address = normalize_text(
        row.get("business_address", "")
    )

    candidate_scores = {}


    # ========================================================
    # HELPER: ADD CANDIDATES
    # ========================================================

    def add_candidates(rows, signal, weight):

        for candidate_row in rows:

            candidate_id = str(
                candidate_row[0]
            )

            # Don't match S1 against itself
            if candidate_id == entity_id:
                continue

            if candidate_id not in candidate_scores:

                candidate_scores[candidate_id] = {
                    "score": 0.0,
                    "signals": set()
                }

            candidate_scores[candidate_id]["score"] += weight

            candidate_scores[candidate_id]["signals"].add(
                signal
            )


    # ========================================================
    # A. NAME PREFIX BLOCK
    # ========================================================

    if country and name:

        prefix = name[:4]

        if prefix:

            rows = conn.execute(
                """
                SELECT entity_id
                FROM name_prefix_index
                WHERE block_key = ?
                """,
                (
                    country + "|" + prefix,
                )
            ).fetchall()

            add_candidates(
                rows,
                "name_prefix",
                3.0
            )


    # ========================================================
    # B. MULTIPLE NAME TOKEN BLOCKS
    # ========================================================

    if country and name:

        tokens = [
            token
            for token in set(name.split())
            if len(token) >= 3
        ]

        # Longer tokens are generally more informative
        tokens.sort(
            key=len,
            reverse=True
        )

        # Use maximum 5 strongest tokens
        for token in tokens[:5]:

            rows = conn.execute(
                """
                SELECT entity_id
                FROM name_token_index
                WHERE block_key = ?
                """,
                (
                    country + "|" + token,
                )
            ).fetchall()

            # Longer tokens receive slightly higher weight
            weight = min(
                5.0,
                2.0 + len(token) / 5.0
            )

            add_candidates(
                rows,
                "name_token",
                weight
            )


    # ========================================================
    # C. ADDRESS TOKEN BLOCKS
    # ========================================================

    if country and address:

        address_tokens = [
            token
            for token in set(address.split())
            if len(token) >= 5
            and not token.isdigit()
        ]

        # Most informative/longest tokens first
        address_tokens.sort(
            key=len,
            reverse=True
        )

        # Use maximum 8 address tokens
        for token in address_tokens[:8]:

            rows = conn.execute(
                """
                SELECT entity_id
                FROM address_token_index
                WHERE block_key = ?
                """,
                (
                    country + "|" + token,
                )
            ).fetchall()

            weight = min(
                4.0,
                1.5 + len(token) / 6.0
            )

            add_candidates(
                rows,
                "address_token",
                weight
            )


    # ========================================================
    # D. RANK CANDIDATES
    # ========================================================

    ranked = []

    for candidate_id, info in candidate_scores.items():

        signals = info["signals"]

        score = info["score"]


        # ----------------------------------------------------
        # Bonus for name prefix
        # ----------------------------------------------------

        if "name_prefix" in signals:

            score += 2.0


        # ----------------------------------------------------
        # Bonus for name token
        # ----------------------------------------------------

        if "name_token" in signals:

            score += 2.0


        # ----------------------------------------------------
        # Bonus for address token
        # ----------------------------------------------------

        if "address_token" in signals:

            score += 2.0


        # ----------------------------------------------------
        # Strong combination:
        # name + address
        # ----------------------------------------------------

        if (
            "name_token" in signals
            and
            "address_token" in signals
        ):

            score += 6.0


        # ----------------------------------------------------
        # Multiple independent signals
        # ----------------------------------------------------

        signal_count = len(signals)

        if signal_count >= 3:

            score += 8.0


        ranked.append(
            (
                candidate_id,
                score,
                signal_count
            )
        )


    # ========================================================
    # SORT
    # ========================================================

    ranked.sort(
        key=lambda x: (
            x[2],   # number of signals
            x[1]    # total score
        ),
        reverse=True
    )


    # ========================================================
    # RETURN TOP CANDIDATES
    # ========================================================

    return set(
        candidate_id
        for candidate_id, score, signal_count
        in ranked[:max_candidates]
    )


print("V3 candidate generator ready.")

V3 candidate generator ready.

In [101]:
print(
    "V3 exists:",
    "get_candidates_for_s1_v3" in globals()
)

V3 exists: True

In [103]:
# ============================================================
# CREATE NAME TOKEN INDEX
# ============================================================

conn.execute("""
CREATE TABLE IF NOT EXISTS name_token_index (
    block_key TEXT,
    entity_id TEXT
)
""")

conn.execute("""
CREATE INDEX IF NOT EXISTS idx_name_token
ON name_token_index(block_key)
""")

conn.commit()

print("name_token_index created successfully.")

name_token_index created successfully.

In [104]:
name_token_count = conn.execute("""
    SELECT COUNT(*)
    FROM name_token_index
""").fetchone()[0]

print("name_token_index rows:", f"{name_token_count:,}")

name_token_index rows: 0

In [106]:
# ============================================================
# TASK 5 - V3 WEIGHTED CANDIDATE GENERATOR
# USING EXISTING SQLITE INDEXES ONLY
# ============================================================

def get_candidates_for_s1_v3(row, max_candidates=20_000):

    entity_id = str(row["entity_id"])

    country = normalize_text(
        row.get("country", "")
    )

    name = normalize_text(
        row.get("business_name", "")
    )

    address = normalize_text(
        row.get("business_address", "")
    )

    candidate_scores = {}


    # ========================================================
    # HELPER
    # ========================================================

    def add_candidates(rows, signal, weight):

        for candidate_row in rows:

            candidate_id = str(candidate_row[0])

            if candidate_id == entity_id:
                continue

            if candidate_id not in candidate_scores:

                candidate_scores[candidate_id] = {
                    "score": 0.0,
                    "signals": set()
                }

            candidate_scores[candidate_id]["score"] += weight
            candidate_scores[candidate_id]["signals"].add(signal)


    # ========================================================
    # 1. NAME PREFIX
    # ========================================================

    if country and name:

        prefix = name[:4]

        rows = conn.execute(
            """
            SELECT entity_id
            FROM name_prefix_index
            WHERE block_key = ?
            """,
            (country + "|" + prefix,)
        ).fetchall()

        add_candidates(
            rows,
            "name_prefix",
            3.0
        )


    # ========================================================
    # 2. FIRST NAME TOKEN
    # ========================================================

    if country and name:

        tokens = [
            token
            for token in name.split()
            if len(token) >= 3
        ]

        if tokens:

            # Use the longest/most informative token
            first_token = sorted(
                set(tokens),
                key=len,
                reverse=True
            )[0]

            rows = conn.execute(
                """
                SELECT entity_id
                FROM first_token_index
                WHERE block_key = ?
                """,
                (country + "|" + first_token,)
            ).fetchall()

            add_candidates(
                rows,
                "first_token",
                2.0
            )


    # ========================================================
    # 3. ADDRESS TOKENS
    # ========================================================

    if country and address:

        address_tokens = [
            token
            for token in set(address.split())
            if len(token) >= 5
            and not token.isdigit()
        ]

        address_tokens.sort(
            key=len,
            reverse=True
        )

        for token in address_tokens[:8]:

            rows = conn.execute(
                """
                SELECT entity_id
                FROM address_token_index
                WHERE block_key = ?
                """,
                (country + "|" + token,)
            ).fetchall()

            weight = min(
                4.0,
                1.5 + len(token) / 6.0
            )

            add_candidates(
                rows,
                "address_token",
                weight
            )


    # ========================================================
    # 4. RANK
    # ========================================================

    ranked = []

    for candidate_id, info in candidate_scores.items():

        score = info["score"]
        signals = info["signals"]

        # Stronger evidence from multiple signals
        if len(signals) >= 2:
            score += 5.0

        if len(signals) >= 3:
            score += 8.0

        ranked.append(
            (
                candidate_id,
                score,
                len(signals)
            )
        )


    # ========================================================
    # 5. SORT
    # ========================================================

    ranked.sort(
        key=lambda x: (
            x[2],
            x[1]
        ),
        reverse=True
    )


    # ========================================================
    # 6. RETURN
    # ========================================================

    return set(
        candidate_id
        for candidate_id, score, signal_count
        in ranked[:max_candidates]
    )


print("V3 weighted candidate generator ready.")

V3 weighted candidate generator ready.

In [109]:
ground_truth = ground_truth_sample.copy()

In [108]:
print("ground_truth shape:", ground_truth.shape)
print("ground_truth columns:", list(ground_truth.columns))

ground_truth shape: (20000, 2)
ground_truth columns: ['source1_entity_id', 'matched_entity_ids']

In [113]:
print("S1 evaluation IDs:")
print(s1_eval["entity_id"].head(10).tolist())

print()

print("Ground truth S1 IDs:")
print(
    ground_truth["source1_entity_id"].head(10).tolist()
)

S1 evaluation IDs:
['S1-708796012', 'S1-387694500', 'S1-973233920', 'S1-769172378', 'S1-436985273', 'S1-287666599', 'S1-131038804', 'S1-460033462', 'S1-942301043', 'S1-535787043']

Ground truth S1 IDs:
['S1-965667', 'S1-55344266', 'S1-343815751', 'S1-656753428', 'S1-102811957', 'S1-18727616', 'S1-318373630', 'S1-86989137', 'S1-29845983', 'S1-789009573']

In [114]:
print("S1 evaluation IDs:")
print(s1_eval["entity_id"].head(10).tolist())

print()

print("Ground truth S1 IDs:")
print(
    ground_truth["source1_entity_id"].head(10).tolist()
)

S1 evaluation IDs:
['S1-708796012', 'S1-387694500', 'S1-973233920', 'S1-769172378', 'S1-436985273', 'S1-287666599', 'S1-131038804', 'S1-460033462', 'S1-942301043', 'S1-535787043']

Ground truth S1 IDs:
['S1-965667', 'S1-55344266', 'S1-343815751', 'S1-656753428', 'S1-102811957', 'S1-18727616', 'S1-318373630', 'S1-86989137', 'S1-29845983', 'S1-789009573']

In [115]:
print("s1_eval shape:", s1_eval.shape)
print("ground_truth shape:", ground_truth.shape)

print("\nGround truth IDs:")
print(ground_truth["source1_entity_id"].head(5).tolist())

s1_eval shape: (20000, 5)
ground_truth shape: (20000, 2)

Ground truth IDs:
['S1-965667', 'S1-55344266', 'S1-343815751', 'S1-656753428', 'S1-102811957']

In [116]:
gt_s1_ids = set(
    ground_truth["source1_entity_id"].astype(str)
)

s1_eval_ids = set(
    s1_eval["entity_id"].astype(str)
)

print("Ground truth S1 IDs:", len(gt_s1_ids))
print("S1 evaluation IDs:", len(s1_eval_ids))
print("Common IDs:", len(gt_s1_ids & s1_eval_ids))

Ground truth S1 IDs: 20000
S1 evaluation IDs: 20000
Common IDs: 184

In [118]:
# Find variables that may contain the original S1 dataset

possible_s1_variables = []

for name, value in list(globals().items()):

    if hasattr(value, "columns"):

        columns = set(value.columns)

        if "entity_id" in columns:

            possible_s1_variables.append(
                (name, value.shape, list(value.columns))
            )

print("Possible S1 dataframes:")

for item in possible_s1_variables:
    print("\nVariable:", item[0])
    print("Shape:", item[1])
    print("Columns:", item[2])

Possible S1 dataframes:

Variable: s1_sample
Shape: (20000, 5)
Columns: ['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']

Variable: chunk
Shape: (6821, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

Variable: matches
Shape: (59, 4)
Columns: ['entity_id', 'business_name', 'business_address', 'country']

Variable: s1_eval
Shape: (20000, 5)
Columns: ['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']

Variable: test_subset
Shape: (100, 5)
Columns: ['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']

Variable: original_row
Shape: (1, 5)
Columns: ['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']

Variable: train_subset
Shape: (5000, 5)
Columns: ['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']

Variable: test_s1
Shape: (100, 5)
Columns: ['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']

Variable: test_records
Shape: (100, 5)
Columns: ['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']

In [119]:
print("s1_sample IDs:")
print(s1_sample["entity_id"].head(10).tolist())

print("\nground_truth IDs:")
print(ground_truth["source1_entity_id"].head(10).tolist())

common_ids = set(
    s1_sample["entity_id"].astype(str)
).intersection(
    set(ground_truth["source1_entity_id"].astype(str))
)

print("\nCommon IDs:", len(common_ids))

s1_sample IDs:
['S1-925783039', 'S1-773889195', 'S1-377745466', 'S1-133037285', 'S1-755362802', 'S1-851869949', 'S1-785847572', 'S1-27541239', 'S1-629417405', 'S1-22305073']

ground_truth IDs:
['S1-965667', 'S1-55344266', 'S1-343815751', 'S1-656753428', 'S1-102811957', 'S1-18727616', 'S1-318373630', 'S1-86989137', 'S1-29845983', 'S1-789009573']

Common IDs: 186

In [120]:
print(s1_sample[["entity_id", "matched_entity_ids"]].head(10))

      entity_id matched_entity_ids
0  S1-925783039
1  S1-773889195
2  S1-377745466
3  S1-133037285
4  S1-755362802
5  S1-851869949
6  S1-785847572
7   S1-27541239
8  S1-629417405
9   S1-22305073

In [121]:
gt_ids = set(
    ground_truth["source1_entity_id"].astype(str)
)

print("Looking for dataframe containing ground-truth S1 IDs...\n")

for name, value in list(globals().items()):

    if hasattr(value, "columns"):

        columns = set(value.columns)

        if "entity_id" in columns:

            try:
                ids = set(value["entity_id"].astype(str))

                overlap = len(
                    gt_ids.intersection(ids)
                )

                if overlap > 0:
                    print(
                        f"{name:25} "
                        f"shape={value.shape} "
                        f"overlap={overlap}"
                    )

            except Exception:
                pass

Looking for dataframe containing ground-truth S1 IDs...

s1_sample                 shape=(20000, 5) overlap=186
chunk                     shape=(6821, 4) overlap=57
matches                   shape=(59, 4) overlap=2
s1_eval                   shape=(20000, 5) overlap=184
train_subset              shape=(5000, 5) overlap=47

In [122]:
print("GROUND TRUTH SAMPLE")
print(ground_truth.head(10).to_string())

print("\nGROUND TRUTH TYPES")
print(ground_truth.dtypes)

print("\nS1 EVAL SAMPLE")
print(s1_eval.head(10).to_string())

print("\nS1 SAMPLE SAMPLE")
print(s1_sample.head(10).to_string())

GROUND TRUTH SAMPLE
  source1_entity_id                                                             matched_entity_ids
0         S1-965667                S2-681193310,S2-743505751,S3-775321672,S3-11291185,S3-860443364
1       S1-55344266                            S2-249013014,S2-197070651,S3-478195123,S3-384364074
2      S1-343815751                                         S2-790675320,S2-479876582,S3-878454467
3      S1-656753428                                          S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-728090388,S3-928796641,S3-449308785
5       S1-18727616                            S2-755677256,S3-187831601,S3-641489370,S3-476250621
6      S1-318373630                                                      S2-660036492,S3-804600254
7       S1-86989137                                                      S3-274817120,S3-312496301
8       S1-29845983                                                      S2-648035184,S3-588502663
9      S1-789009573                                          S2-383871912,S3-74481402,S3-576451439

GROUND TRUTH TYPES
source1_entity_id     string[python]
matched_entity_ids    string[python]
dtype: object

S1 EVAL SAMPLE
      entity_id                    business_name                                                                                                              business_address country                                                                                                            matched_entity_ids
0  S1-708796012        Board of Consumer Affairs                                                                          122 Dayton Yellow Springs Road, Unit 4, Fairborn, OH      US                                                 S2-994438467,S2-440628035,S3-338279058,S3-335174066,S3-703951662,S3-974934575
1  S1-387694500     Bombay Power Private Limited  No: 32/2, 2Nd Floor, Mcc Towers, Opp To Sigma Soft Tech Park, Whitefield Main Road, Ramagon, Danahalli, Bangalore, Karnataka   India  S2-89272121,S2-828925482,S2-960848454,S2-674345300,S3-789542813,S3-9126403,S3-469722658,S3-904486811,S3-77197957,S3-91755708
2  S1-973233920          Data Materials Networks                                                                                                609 Hickory Street, Ottawa, KS      US                                                                           S2-428307002,S3-110090880,S3-159133847,S3-792460305
3  S1-769172378  Technocast Chit Private Limited                                                  A/39, Kamla Nagar, Near Ram Mandir, Kotra Sultanabad, Bhopal, Madhya Pradesh   India                                                                                        S2-977119232,S2-754328130,S2-713014713
4  S1-436985273                   Corner Pilates                                                                                              KY, 116 Redwood Drive, Frankfort      US                                                                                                     S2-488930867,S3-150259143
5  S1-287666599             Bates Generation LLC                                                                                     25943 Highland Road, Richmond Heights, OH      US                                                              S2-207356341,S2-107690465,S2-594570026,S3-517645522,S3-737314411
6  S1-131038804   Torres Heartland Northland LLC                                                                                     5515 Strawberry Hill Drive, Charlotte, NC      US                                                                           S2-655191371,S3-766103665,S3-508705806,S3-193182438
7  S1-460033462     FYJ Apparels Private Limited                                                                               No.1 19Th Street K.K.Nagar, Chennai, Tamil Nadu   India                                                                                         S2-985336551,S3-68319127,S3-280691790
8  S1-942301043               Qunaque Realty LLC                                                                                                         102 Spencer, Mesa, AZ      US                                                                                        S2-789520489,S2-438042920,S3-932179721
9  S1-535787043              Summit Freight P.C.                                                                                              6507 Western Avenue, Chicago, IL      US

S1 SAMPLE SAMPLE
      entity_id                             business_name                                                                                                           business_address country matched_entity_ids
0  S1-925783039                       Orelee's Barbershop                                                                                     1795 Westchester Drive, High Point, NC      US
1  S1-773889195                               Prime Money                                                                                            17560 Ellis Road, Tahlequah, OK      US
2  S1-377745466                             B+ Retail Inc                                                                                        1712 Montebello Avenue, Phoenix, AZ      US
3  S1-133037285                             Christ Chapel                                                                          2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD      US
4  S1-755362802                   Prabhav Business Center                                                                       797, Lake Town Block A, Kolkata, Howrah, West Bengal   India
5  S1-851869949                Custom Wealth Services LLC                                                                                          OH, Columbus, 5559 Orville Avenue      US
6  S1-785847572  Consulting Nyasa Nursing Private Limited  2505, Tower 1, Oakwood, Runwal Greens, Mulund Goreagon Link Road, Near Fortis Hospital, Bhandup West, Mumbai, Maharashtra   India
7   S1-27541239                         Nexus Anchor Rain                                                                               1111 Church Street, Unit 2007, Nashville, TN      US
8  S1-629417405                         Moore Bitwise Inc                                                                                      337 Oakland Avenue, Michigan City, IN      US
9   S1-22305073                Dermatology Green Medicine                                                                294 Meadowcreek Drive, Unit Unit 2, Village Of Pewaukee, WI      US

In [123]:
# Find all variables that look like data sources/files

for name, value in list(globals().items()):

    # Skip private/internal variables
    if name.startswith("_"):
        continue

    # DataFrames
    if hasattr(value, "shape") and hasattr(value, "columns"):
        print(
            f"DATAFRAME  {name:30} "
            f"shape={value.shape} "
            f"columns={list(value.columns)}"
        )

    # Lists of file paths / strings
    elif isinstance(value, (list, tuple)):
        if len(value) > 0:
            sample = value[:3]
            if any(isinstance(x, str) for x in sample):
                print(
                    f"LIST       {name:30} "
                    f"length={len(value)} "
                    f"sample={sample}"
                )

    # Strings that may contain paths
    elif isinstance(value, str):
        lower = value.lower()

        if any(
            keyword in lower
            for keyword in [
                ".csv",
                ".parquet",
                ".json",
                ".xlsx",
                "source1",
                "source_1",
                "s1"
            ]
        ):
            print(
                f"STRING     {name:30} = {value}"
            )

LIST       In                             length=124 sample=['', 'process_source_file(\n    os.path.join(DATA_DIR, "train_source2.tsv"),\n    "S2"\n)', 'CHUNK_SIZE = 50_000\n\n\ndef process_source_file(filepath, source_name):\n\n    print(f"\\nProcessing {source_name}")\n    print(filepath)\n\n    total = 0\n\n    for chunk in pd.read_csv(\n        filepath,\n        sep="\\t",\n        dtype="string",\n        chunksize=CHUNK_SIZE\n    ):\n\n        chunk = chunk.fillna("")\n\n        chunk["clean_name"] = normalize_series(\n            chunk["business_name"]\n        )\n\n        chunk["clean_address"] = normalize_series(\n            chunk["business_address"]\n        )\n\n        # Insert main records\n        records = list(\n            zip(\n                chunk["entity_id"],\n                [source_name] * len(chunk),\n                chunk["business_name"],\n                chunk["business_address"],\n                chunk["country"],\n                chunk["clean_name"],\n                chunk["clean_address"]\n            )\n        )\n\n        conn.executemany("""\n            INSERT OR REPLACE INTO entities\n            VALUES (?, ?, ?, ?, ?, ?, ?)\n        """, records)\n\n        # Blocking indexes\n        prefix_records = []\n        first_records = []\n        address_records = []\n\n        for row in chunk.itertuples(index=False):\n\n            country = normalize_text(row.country)\n            name = row.clean_name\n            address = row.clean_address\n\n            if country and name:\n\n                prefix = name[:4]\n\n                if prefix:\n                    prefix_records.append(\n                        (country + "|" + prefix, row.entity_id)\n                    )\n\n                first = name.split()[0]\n\n                if len(first) >= 3:\n                    first_records.append(\n                        (country + "|" + first, row.entity_id)\n                    )\n\n            if country and address:\n\n                tokens = address.split()\n\n                # Use several useful address tokens\n                used = set()\n\n                for token in tokens:\n\n                    if len(token) < 5:\n                        continue\n\n                    if token.isdigit():\n                        continue\n\n                    if token in used:\n                        continue\n\n                    used.add(token)\n\n                    address_records.append(\n                        (country + "|" + token, row.entity_id)\n                    )\n\n                    # Prevent huge address indexes\n                    if len(used) >= 3:\n                        break\n\n        if prefix_records:\n            conn.executemany("""\n                INSERT INTO name_prefix_index\n                VALUES (?, ?)\n            """, prefix_records)\n\n        if first_records:\n            conn.executemany("""\n                INSERT INTO first_token_index\n                VALUES (?, ?)\n            """, first_records)\n\n        if address_records:\n            conn.executemany("""\n                INSERT INTO address_token_index\n                VALUES (?, ?)\n            """, address_records)\n\n        conn.commit()\n\n        total += len(chunk)\n\n        del chunk\n        del records\n        del prefix_records\n        del first_records\n        del address_records\n\n        gc.collect()\n\n        if total % 500_000 < CHUNK_SIZE:\n            print(f"Processed {total:,} rows")\n\n\n    print(f"Finished {source_name}: {total:,} rows")']
LIST       table                          length=1 sample=('name_prefix_index',)
DATAFRAME  source_counts                  shape=(2, 2) columns=['source', 'count']
DATAFRAME  s1_sample                      shape=(20000, 5) columns=['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']
DATAFRAME  ground_truth_sample            shape=(20000, 2) columns=['source1_entity_id', 'matched_entity_ids']
DATAFRAME  gt_eval                        shape=(20000, 2) columns=['source1_entity_id', 'matched_entity_ids']
DATAFRAME  chunk                          shape=(6821, 4) columns=['entity_id', 'business_name', 'business_address', 'country']
DATAFRAME  matches                        shape=(59, 4) columns=['entity_id', 'business_name', 'business_address', 'country']
DATAFRAME  s1_eval                        shape=(20000, 5) columns=['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']
DATAFRAME  test_subset                    shape=(100, 5) columns=['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']
LIST       name_parts                     length=4 sample=['board', 'of', 'consumer']
DATAFRAME  missed_df                      shape=(45, 15) columns=['s1_id', 's1_name', 's1_address', 's1_country', 'missing_id', 'candidate_id', 'source', 'business_name', 'business_address', 'country', 'country_match', 'prefix_hit', 'first_token_hit', 'address_token_hits', 'total_address_hits']
LIST       reasons                        length=4 sample=['country matched', 'name prefix blocking failed', 'first-token blocking failed']
DATAFRAME  original_row                   shape=(1, 5) columns=['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']
DATAFRAME  fast_analysis_df               shape=(45, 6) columns=['s1_id', 'true_id', 'prefix_hit', 'first_token_hit', 'address_hits', 'reason']
DATAFRAME  train_subset                   shape=(5000, 5) columns=['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']
DATAFRAME  test_s1                        shape=(100, 5) columns=['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']
STRING     s1_id                          = S1-708796012
LIST       test_s1_ids                    length=100 sample=['S1-708796012', 'S1-387694500', 'S1-973233920']
DATAFRAME  ground_truth                   shape=(20000, 2) columns=['source1_entity_id', 'matched_entity_ids']
DATAFRAME  gt_for_s1                      shape=(0, 2) columns=['source1_entity_id', 'matched_entity_ids']
LIST       required_variables             length=3 sample=['s1_eval', 'ground_truth', 'get_candidates_for_s1_v3']
STRING     variable                       = get_candidates_for_s1_v3
LIST       required_gt_columns            length=2 sample=['source1_entity_id', 'matched_entity_ids']
DATAFRAME  test_records                   shape=(100, 5) columns=['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids']
STRING     source1_id                     = S1-587000615
LIST       item                           length=3 sample=('test_records', (100, 5), ['entity_id', 'business_name', 'business_address', 'country', 'matched_entity_ids'])

In [124]:
gt_ids = set(
    ground_truth["source1_entity_id"].astype(str)
)

print("Ground truth IDs:", len(gt_ids))

placeholders = ",".join(["?"] * len(gt_ids))

rows = conn.execute(
    f"""
    SELECT entity_id, business_name, business_address, country
    FROM entities
    WHERE source = 'S1'
      AND entity_id IN ({placeholders})
    """,
    list(gt_ids)
).fetchall()

print("S1 records found in SQLite:", len(rows))

Ground truth IDs: 20000
S1 records found in SQLite: 0

In [125]:
print("Tables in SQLite:")

tables = conn.execute("""
    SELECT name
    FROM sqlite_master
    WHERE type = 'table'
    ORDER BY name
""").fetchall()

for table in tables:
    print(table[0])

Tables in SQLite:
address_token_index
entities
first_token_index
name_prefix_index
name_token_index

In [126]:
print("\nEntity counts by source:")

source_counts_db = conn.execute("""
    SELECT source, COUNT(*)
    FROM entities
    GROUP BY source
    ORDER BY source
""").fetchall()

for row in source_counts_db:
    print(row)

Entity counts by source:
('S2', 5034616)
('S3', 5285603)

In [127]:
print("\nFirst 10 S1 records currently in SQLite:")

rows = conn.execute("""
    SELECT entity_id, business_name, business_address, country
    FROM entities
    WHERE source = 'S1'
    LIMIT 10
""").fetchall()

for row in rows:
    print(row)

First 10 S1 records currently in SQLite:

In [128]:
print("=== ENTITY COUNTS BY SOURCE ===")

source_counts_db = conn.execute("""
    SELECT source, COUNT(*)
    FROM entities
    GROUP BY source
    ORDER BY source
""").fetchall()

for source, count in source_counts_db:
    print(f"{source}: {count:,}")


print("\n=== FIRST 10 S1 RECORDS ===")

rows = conn.execute("""
    SELECT entity_id, business_name, business_address, country
    FROM entities
    WHERE source = 'S1'
    LIMIT 10
""").fetchall()

for row in rows:
    print(row)

=== ENTITY COUNTS BY SOURCE ===
S2: 5,034,616
S3: 5,285,603

=== FIRST 10 S1 RECORDS ===

In [129]:
import os

print("DATA_DIR:", DATA_DIR)
print("\nFiles in DATA_DIR:")

for filename in os.listdir(DATA_DIR):
    print(filename)

DATA_DIR: /home/sagemaker-user/Igniters_submission_file

Files in DATA_DIR:
output
code
Documentation_template.md
.git
.gitignore
.DS_Store
train_source1.tsv
train_source3.tsv
train_ground_truth.tsv
train_source2.tsv
test_source3.tsv
test_source1.tsv
test_source2.tsv
entity_index.db

In [130]:
import pandas as pd

s1_check = pd.read_csv(
    os.path.join(DATA_DIR, "train_source1.tsv"),
    sep="\t",
    dtype="string",
    nrows=5
)

print(s1_check)
print("\nColumns:")
print(s1_check.columns.tolist())

      entity_id            business_name  \
0  S1-925783039      Orelee's Barbershop
1  S1-773889195              Prime Money
2  S1-377745466            B+ Retail Inc
3  S1-133037285            Christ Chapel
4  S1-755362802  Prabhav Business Center

                                    business_address country
0             1795 Westchester Drive, High Point, NC      US
1                    17560 Ellis Road, Tahlequah, OK      US
2                1712 Montebello Avenue, Phoenix, AZ      US
3  2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD      US
4  797, Lake Town Block A, Kolkata, Howrah, West ...   India

Columns:
['entity_id', 'business_name', 'business_address', 'country']

In [131]:
gt_ids = set(
    ground_truth["source1_entity_id"].astype(str)
)

s1_ids_check = set(
    pd.read_csv(
        os.path.join(DATA_DIR, "train_source1.tsv"),
        sep="\t",
        dtype="string",
        usecols=["entity_id"]
    )["entity_id"].astype(str)
)

print("Ground truth IDs:", len(gt_ids))
print("S1 file IDs:", len(s1_ids_check))
print("Common IDs:", len(gt_ids.intersection(s1_ids_check)))

Ground truth IDs: 20000
S1 file IDs: 2206821
Common IDs: 20000

In [132]:
# ============================================================
# LOAD TRAIN SOURCE 1 INTO EXISTING SQLITE DATABASE
# ============================================================

import os
import gc
import pandas as pd

S1_FILE = os.path.join(DATA_DIR, "train_source1.tsv")
CHUNK_SIZE = 50_000

print("Loading:", S1_FILE)

total = 0

for chunk in pd.read_csv(
    S1_FILE,
    sep="\t",
    dtype="string",
    chunksize=CHUNK_SIZE
):

    chunk = chunk.fillna("")

    # Normalize fields
    chunk["clean_name"] = normalize_series(
        chunk["business_name"]
    )

    chunk["clean_address"] = normalize_series(
        chunk["business_address"]
    )

    # --------------------------------------------------------
    # INSERT MAIN S1 RECORDS
    # --------------------------------------------------------

    records = list(
        zip(
            chunk["entity_id"],
            ["S1"] * len(chunk),
            chunk["business_name"],
            chunk["business_address"],
            chunk["country"],
            chunk["clean_name"],
            chunk["clean_address"]
        )
    )

    conn.executemany(
        """
        INSERT OR REPLACE INTO entities
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        records
    )

    # --------------------------------------------------------
    # BUILD INDEX RECORDS
    # --------------------------------------------------------

    prefix_records = []
    first_records = []
    address_records = []

    for row in chunk.itertuples(index=False):

        country = normalize_text(row.country)
        name = row.clean_name
        address = row.clean_address

        # NAME PREFIX + FIRST TOKEN
        if country and name:

            prefix = name[:4]

            if prefix:
                prefix_records.append(
                    (
                        country + "|" + prefix,
                        row.entity_id
                    )
                )

            first = name.split()[0]

            if len(first) >= 3:
                first_records.append(
                    (
                        country + "|" + first,
                        row.entity_id
                    )
                )

        # ADDRESS TOKENS
        if country and address:

            tokens = address.split()

            used = set()

            for token in tokens:

                if len(token) < 5:
                    continue

                if token.isdigit():
                    continue

                if token in used:
                    continue

                used.add(token)

                address_records.append(
                    (
                        country + "|" + token,
                        row.entity_id
                    )
                )

                if len(used) >= 3:
                    break

    # --------------------------------------------------------
    # INSERT INDEXES
    # --------------------------------------------------------

    if prefix_records:
        conn.executemany(
            """
            INSERT INTO name_prefix_index
            VALUES (?, ?)
            """,
            prefix_records
        )

    if first_records:
        conn.executemany(
            """
            INSERT INTO first_token_index
            VALUES (?, ?)
            """,
            first_records
        )

    if address_records:
        conn.executemany(
            """
            INSERT INTO address_token_index
            VALUES (?, ?)
            """,
            address_records
        )

    conn.commit()

    total += len(chunk)

    print(f"Processed {total:,} S1 records")

    del chunk
    del records
    del prefix_records
    del first_records
    del address_records

    gc.collect()

print("\nFinished loading S1.")
print(f"Total S1 records loaded: {total:,}")

Loading: /home/sagemaker-user/Igniters_submission_file/train_source1.tsv
Processed 50,000 S1 records
Processed 100,000 S1 records
Processed 150,000 S1 records
Processed 200,000 S1 records
Processed 250,000 S1 records
Processed 300,000 S1 records
Processed 350,000 S1 records
Processed 400,000 S1 records
Processed 450,000 S1 records
Processed 500,000 S1 records
Processed 550,000 S1 records
Processed 600,000 S1 records
Processed 650,000 S1 records
Processed 700,000 S1 records
Processed 750,000 S1 records
Processed 800,000 S1 records
Processed 850,000 S1 records
Processed 900,000 S1 records
Processed 950,000 S1 records
Processed 1,000,000 S1 records
Processed 1,050,000 S1 records
Processed 1,100,000 S1 records
Processed 1,150,000 S1 records
Processed 1,200,000 S1 records
Processed 1,250,000 S1 records
Processed 1,300,000 S1 records
Processed 1,350,000 S1 records
Processed 1,400,000 S1 records
Processed 1,450,000 S1 records
Processed 1,500,000 S1 records
Processed 1,550,000 S1 records
Processed 1,600,000 S1 records
Processed 1,650,000 S1 records
Processed 1,700,000 S1 records
Processed 1,750,000 S1 records
Processed 1,800,000 S1 records
Processed 1,850,000 S1 records
Processed 1,900,000 S1 records
Processed 1,950,000 S1 records
Processed 2,000,000 S1 records
Processed 2,050,000 S1 records
Processed 2,100,000 S1 records
Processed 2,150,000 S1 records
Processed 2,200,000 S1 records
Processed 2,206,821 S1 records

Finished loading S1.
Total S1 records loaded: 2,206,821

In [133]:
# ============================================================
# STEP 6 - CANDIDATE RECALL EVALUATION
# USING V3 CANDIDATE GENERATOR
# ============================================================

import pandas as pd
import os

print("Starting Step 6...")

# ------------------------------------------------------------
# 1. GET THE 20,000 GROUND-TRUTH S1 IDs
# ------------------------------------------------------------

gt_ids = set(
    ground_truth["source1_entity_id"].astype(str)
)

print("Ground-truth S1 IDs:", len(gt_ids))


# ------------------------------------------------------------
# 2. RETRIEVE THOSE S1 RECORDS FROM SQLITE
# ------------------------------------------------------------

placeholders = ",".join(["?"] * len(gt_ids))

rows = conn.execute(
    f"""
    SELECT
        entity_id,
        business_name,
        business_address,
        country
    FROM entities
    WHERE source = 'S1'
      AND entity_id IN ({placeholders})
    """,
    list(gt_ids)
).fetchall()

s1_eval_correct = pd.DataFrame(
    rows,
    columns=[
        "entity_id",
        "business_name",
        "business_address",
        "country"
    ]
)

print("S1 evaluation records:", len(s1_eval_correct))


# ------------------------------------------------------------
# 3. CREATE GROUND-TRUTH LOOKUP
# ------------------------------------------------------------

ground_truth_lookup = dict(
    zip(
        ground_truth["source1_entity_id"].astype(str),
        ground_truth["matched_entity_ids"].fillna("").astype(str)
    )
)


# ------------------------------------------------------------
# 4. EVALUATE FIRST 100 RECORDS
# ------------------------------------------------------------

step6_results = []
missed_matches = []

test_rows = s1_eval_correct.head(100)

print("\nEvaluating", len(test_rows), "S1 records...\n")


for index, (_, s1_row) in enumerate(
    test_rows.iterrows(),
    start=1
):

    s1_id = str(s1_row["entity_id"])

    # True matching S2/S3 IDs
    true_matches = set(
        x.strip()
        for x in ground_truth_lookup.get(
            s1_id,
            ""
        ).split(",")
        if x.strip()
    )

    # Candidate generation
    candidate_ids = get_candidates_for_s1_v3(
        s1_row,
        max_candidates=20_000
    )

    candidate_ids = set(
        str(x)
        for x in candidate_ids
    )

    # Matches recovered by candidate generation
    found_matches = (
        true_matches.intersection(candidate_ids)
    )

    # Recall
    if len(true_matches) > 0:
        recall = (
            len(found_matches)
            / len(true_matches)
        )
    else:
        recall = None

    step6_results.append({
        "s1_id": s1_id,
        "true_count": len(true_matches),
        "found_count": len(found_matches),
        "recall": recall,
        "candidate_count": len(candidate_ids)
    })

    # Save missed true matches
    missing = true_matches - candidate_ids

    for missing_id in missing:

        missed_matches.append({
            "s1_id": s1_id,
            "missing_id": missing_id
        })

    print(
        f"{index}/100 | "
        f"Candidates: {len(candidate_ids)} | "
        f"True: {len(true_matches)} | "
        f"Found: {len(found_matches)} | "
        f"Recall: "
        f"{recall:.2%}" if recall is not None
        else
        f"{index}/100 | "
        f"Candidates: {len(candidate_ids)} | "
        f"True: 0 | "
        f"Found: 0 | "
        f"Recall: N/A"
    )


# ------------------------------------------------------------
# 5. RESULTS DATAFRAME
# ------------------------------------------------------------

step6_results = pd.DataFrame(step6_results)

print("\n========================================")
print("STEP 6 COMPLETE")
print("========================================")

print(
    "Records evaluated:",
    len(step6_results)
)

print(
    "Average recall:",
    step6_results["recall"].dropna().mean()
)

print(
    "Total candidates:",
    step6_results["candidate_count"].sum()
)


# ------------------------------------------------------------
# 6. SAVE MISSED MATCHES
# ------------------------------------------------------------

missed_df = pd.DataFrame(missed_matches)

os.makedirs("analysis", exist_ok=True)

missed_path = "analysis/missed_matches_step6.csv"

missed_df.to_csv(
    missed_path,
    index=False
)

print(
    "\nMissed matches saved to:",
    missed_path
)

Starting Step 6...
Ground-truth S1 IDs: 20000
S1 evaluation records: 20000

Evaluating 100 S1 records...

1/100 | Candidates: 20000 | True: 5 | Found: 4 | Recall: 80.00%
2/100 | Candidates: 20000 | True: 3 | Found: 2 | Recall: 66.67%
3/100 | Candidates: 20000 | True: 3 | Found: 3 | Recall: 100.00%
4/100 | Candidates: 20000 | True: 3 | Found: 1 | Recall: 33.33%
5/100 | Candidates: 20000 | True: 2 | Found: 1 | Recall: 50.00%
6/100 | Candidates: 20000 | True: 4 | Found: 3 | Recall: 75.00%
7/100 | Candidates: 20000 | True: 0 | Found: 0 | Recall: N/A
8/100 | Candidates: 20000 | True: 2 | Found: 2 | Recall: 100.00%
9/100 | Candidates: 20000 | True: 2 | Found: 2 | Recall: 100.00%
10/100 | Candidates: 20000 | True: 4 | Found: 4 | Recall: 100.00%
11/100 | Candidates: 20000 | True: 2 | Found: 2 | Recall: 100.00%
12/100 | Candidates: 20000 | True: 2 | Found: 2 | Recall: 100.00%
13/100 | Candidates: 20000 | True: 8 | Found: 8 | Recall: 100.00%
14/100 | Candidates: 14103 | True: 3 | Found: 3 | Recall: 100.00%
15/100 | Candidates: 17110 | True: 1 | Found: 1 | Recall: 100.00%
16/100 | Candidates: 20000 | True: 3 | Found: 3 | Recall: 100.00%
17/100 | Candidates: 20000 | True: 2 | Found: 2 | Recall: 100.00%
18/100 | Candidates: 20000 | True: 5 | Found: 4 | Recall: 80.00%
19/100 | Candidates: 20000 | True: 3 | Found: 3 | Recall: 100.00%
20/100 | Candidates: 20000 | True: 5 | Found: 5 | Recall: 100.00%
21/100 | Candidates: 20000 | True: 2 | Found: 2 | Recall: 100.00%
22/100 | Candidates: 20000 | True: 2 | Found: 2 | Recall: 100.00%
23/100 | Candidates: 20000 | True: 5 | Found: 5 | Recall: 100.00%
34/100 | Candidates: 20000 | True: 5 | Found: 5 | Recall: 100.00%
35/100 | Candidates: 20000 | True: 3 | Found: 3 | Recall: 100.00%
36/100 | Candidates: 20000 | True: 5 | Found: 5 | Recall: 100.00%
37/100 | Candidates: 20000 | True: 4 | Found: 4 | Recall: 100.00%
38/100 | Candidates: 20000 | True: 0 | Found: 0 | Recall: N/A
39/100 | Candidates: 20000 | True: 6 | Found: 5 | Recall: 83.33%
40/100 | Candidates: 20000 | True: 2 | Found: 2 | Recall: 100.00%
41/100 | Candidates: 20000 | True: 2 | Found: 2 | Recall: 100.00%
42/100 | Candidates: 20000 | True: 3 | Found: 3 | Recall: 100.00%
43/100 | Candidates: 3613 | True: 3 | Found: 3 | Recall: 100.00%
44/100 | Candidates: 20000 | True: 1 | Found: 1 | Recall: 100.00%
45/100 | Candidates: 20000 | True: 5 | Found: 5 | Recall: 100.00%
46/100 | Candidates: 20000 | True: 7 | Found: 7 | Recall: 100.00%
60/100 | Candidates: 20000 | True: 2 | Found: 2 | Recall: 100.00%
61/100 | Candidates: 20000 | True: 3 | Found: 3 | Recall: 100.00%
62/100 | Candidates: 20000 | True: 4 | Found: 4 | Recall: 100.00%
63/100 | Candidates: 6926 | True: 3 | Found: 3 | Recall: 100.00%
64/100 | Candidates: 20000 | True: 7 | Found: 7 | Recall: 100.00%
67/100 | Candidates: 20000 | True: 6 | Found: 6 | Recall: 100.00%
68/100 | Candidates: 20000 | True: 2 | Found: 1 | Recall: 50.00%
69/100 | Candidates: 20000 | True: 0 | Found: 0 | Recall: N/A
70/100 | Candidates: 20000 | True: 3 | Found: 3 | Recall: 100.00%
71/100 | Candidates: 20000 | True: 3 | Found: 3 | Recall: 100.00%
72/100 | Candidates: 20000 | True: 4 | Found: 4 | Recall: 100.00%
73/100 | Candidates: 20000 | True: 4 | Found: 4 | Recall: 100.00%
93/100 | Candidates: 20000 | True: 5 | Found: 4 | Recall: 80.00%
94/100 | Candidates: 20000 | True: 4 | Found: 3 | Recall: 75.00%
95/100 | Candidates: 20000 | True: 6 | Found: 6 | Recall: 100.00%
96/100 | Candidates: 20000 | True: 6 | Found: 6 | Recall: 100.00%
97/100 | Candidates: 20000 | True: 2 | Found: 2 | Recall: 100.00%
98/100 | Candidates: 3878 | True: 2 | Found: 2 | Recall: 100.00%
99/100 | Candidates: 20000 | True: 3 | Found: 2 | Recall: 66.67%
100/100 | Candidates: 20000 | True: 0 | Found: 0 | Recall: N/A

========================================
STEP 6 COMPLETE
========================================
Records evaluated: 100
Average recall: 0.9238351254480287
Total candidates: 1865368

Missed matches saved to: analysis/missed_matches_step6.csv

In [134]:
# ============================================================
# STEP 7 — ANALYZE WHY MATCHES WERE MISSED
# ============================================================

print("Starting Step 7...")

# ------------------------------------------------------------
# 1. FUNCTION: CHECK BLOCK EVIDENCE FOR A TRUE MATCH
# ------------------------------------------------------------

def get_block_evidence_v3(s1_row, candidate_id):

    country = normalize_text(
        s1_row.get("country", "")
    )

    name = normalize_text(
        s1_row.get("business_name", "")
    )

    address = normalize_text(
        s1_row.get("business_address", "")
    )

    # --------------------------------------------------------
    # GET CANDIDATE RECORD
    # --------------------------------------------------------

    candidate = conn.execute(
        """
        SELECT
            entity_id,
            source,
            business_name,
            business_address,
            country,
            clean_name,
            clean_address
        FROM entities
        WHERE entity_id = ?
        """,
        (str(candidate_id),)
    ).fetchone()

    if candidate is None:
        return None

    (
        entity_id,
        source,
        business_name,
        business_address,
        candidate_country,
        clean_name,
        clean_address
    ) = candidate

    candidate_country_norm = normalize_text(
        candidate_country
    )

    # --------------------------------------------------------
    # COUNTRY MATCH
    # --------------------------------------------------------

    country_match = (
        country != ""
        and candidate_country_norm == country
    )

    # --------------------------------------------------------
    # 1. NAME PREFIX
    # Same logic as V3
    # --------------------------------------------------------

    prefix_hit = False

    if country and name:

        prefix = name[:4]

        result = conn.execute(
            """
            SELECT 1
            FROM name_prefix_index
            WHERE block_key = ?
              AND entity_id = ?
            LIMIT 1
            """,
            (
                country + "|" + prefix,
                str(candidate_id)
            )
        ).fetchone()

        prefix_hit = result is not None

    # --------------------------------------------------------
    # 2. FIRST TOKEN
    # Same logic as V3:
    # longest token of length >= 3
    # --------------------------------------------------------

    first_token_hit = False
    selected_first_token = ""

    if country and name:

        tokens = [
            token
            for token in name.split()
            if len(token) >= 3
        ]

        if tokens:

            selected_first_token = sorted(
                set(tokens),
                key=len,
                reverse=True
            )[0]

            result = conn.execute(
                """
                SELECT 1
                FROM first_token_index
                WHERE block_key = ?
                  AND entity_id = ?
                LIMIT 1
                """,
                (
                    country + "|" + selected_first_token,
                    str(candidate_id)
                )
            ).fetchone()

            first_token_hit = result is not None

    # --------------------------------------------------------
    # 3. ADDRESS TOKEN BLOCKS
    # Same token rules as V3
    # --------------------------------------------------------

    address_token_hits = []

    if country and address:

        address_tokens = [
            token
            for token in set(address.split())
            if len(token) >= 5
            and not token.isdigit()
        ]

        address_tokens.sort(
            key=len,
            reverse=True
        )

        for token in address_tokens[:8]:

            result = conn.execute(
                """
                SELECT 1
                FROM address_token_index
                WHERE block_key = ?
                  AND entity_id = ?
                LIMIT 1
                """,
                (
                    country + "|" + token,
                    str(candidate_id)
                )
            ).fetchone()

            if result is not None:
                address_token_hits.append(token)

    # --------------------------------------------------------
    # RETURN EVIDENCE
    # --------------------------------------------------------

    return {
        "candidate_id": str(candidate_id),
        "source": source,
        "business_name": business_name,
        "business_address": business_address,
        "country": candidate_country,
        "country_match": country_match,
        "prefix_hit": prefix_hit,
        "first_token_hit": first_token_hit,
        "address_token_hits": address_token_hits,
        "total_address_hits": len(address_token_hits),
        "selected_first_token": selected_first_token
    }


# ------------------------------------------------------------
# 2. ANALYZE ALL MISSED MATCHES FROM STEP 6
# ------------------------------------------------------------

step7_records = []

print("Analyzing missed matches...")

for idx, missed_row in missed_df.iterrows():

    s1_id = str(missed_row["s1_id"])
    missing_id = str(missed_row["missing_id"])

    # Retrieve complete S1 record from the correctly loaded data
    s1_match = s1_eval_correct[
        s1_eval_correct["entity_id"].astype(str) == s1_id
    ]

    if len(s1_match) == 0:
        continue

    s1_row = s1_match.iloc[0]

    # Get block evidence
    evidence = get_block_evidence_v3(
        s1_row,
        missing_id
    )

    if evidence is None:
        continue

    record = {
        "s1_id": s1_id,
        "s1_name": s1_row["business_name"],
        "s1_address": s1_row["business_address"],
        "s1_country": s1_row["country"],
        "missing_id": missing_id,
        **evidence
    }

    step7_records.append(record)


# ------------------------------------------------------------
# 3. CREATE DATAFRAME
# ------------------------------------------------------------

step7_df = pd.DataFrame(step7_records)


# ------------------------------------------------------------
# 4. CLASSIFY WHY EACH MATCH WAS MISSED
# ------------------------------------------------------------

def classify_miss_v3(row):

    # Country itself does not match
    if not row["country_match"]:
        return "COUNTRY_MISMATCH"

    # At least one existing V3 block can retrieve the
    # true candidate, but Step 6 did not retain it.
    if (
        row["prefix_hit"]
        or row["first_token_hit"]
        or row["total_address_hits"] > 0
    ):
        return "BLOCK_FOUND_BUT_RANKED_OUT"

    # None of the current V3 blocking signals can retrieve it
    return "NO_EXISTING_BLOCK_HIT"


if len(step7_df) > 0:

    step7_df["reason"] = step7_df.apply(
        classify_miss_v3,
        axis=1
    )

else:

    step7_df["reason"] = pd.Series(
        dtype="string"
    )


# ------------------------------------------------------------
# 5. DISPLAY SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 7 COMPLETE")
print("=" * 70)

print(
    "Total missed matches analyzed:",
    len(step7_df)
)

print("\nReason breakdown:")

if len(step7_df) > 0:
    print(
        step7_df["reason"].value_counts()
    )
else:
    print("No missed matches to analyze.")


# ------------------------------------------------------------
# 6. PRINT DETAILS
# ------------------------------------------------------------

for _, r in step7_df.iterrows():

    print("\n" + "=" * 90)

    print("S1:")
    print("ID       :", r["s1_id"])
    print("Name     :", r["s1_name"])
    print("Address  :", r["s1_address"])
    print("Country  :", r["s1_country"])

    print("\nMISSED TRUE MATCH:")
    print("ID       :", r["missing_id"])
    print("Source   :", r["source"])
    print("Name     :", r["business_name"])
    print("Address  :", r["business_address"])
    print("Country  :", r["country"])

    print("\nBLOCK EVIDENCE:")
    print("Country match :", r["country_match"])
    print("Prefix hit    :", r["prefix_hit"])
    print("First token  :", r["first_token_hit"])
    print("Address hits  :", r["address_token_hits"])

    print("\nREASON:")
    print(r["reason"])


# ------------------------------------------------------------
# 7. SAVE STEP 7 RESULTS
# ------------------------------------------------------------

import os

os.makedirs("analysis", exist_ok=True)

step7_output = "analysis/missed_match_analysis_step7.csv"

step7_df.to_csv(
    step7_output,
    index=False
)

print("\nSaved Step 7 results to:")
print(step7_output)

Starting Step 7...
Analyzing missed matches...

KeyboardInterrupt:

In [135]:
# ============================================================
# STEP 7 — OPTIMIZED MISSED MATCH ANALYSIS
# ============================================================

print("Starting optimized Step 7...")

# ------------------------------------------------------------
# 1. FAST BLOCK EVIDENCE FUNCTION
# ------------------------------------------------------------

def get_block_evidence_v3_fast(s1_row, candidate_id):

    candidate_id = str(candidate_id)

    country = normalize_text(
        s1_row.get("country", "")
    )

    name = normalize_text(
        s1_row.get("business_name", "")
    )

    address = normalize_text(
        s1_row.get("business_address", "")
    )

    # --------------------------------------------------------
    # GET CANDIDATE RECORD
    # --------------------------------------------------------

    candidate = conn.execute(
        """
        SELECT
            entity_id,
            source,
            business_name,
            business_address,
            country
        FROM entities
        WHERE entity_id = ?
        LIMIT 1
        """,
        (candidate_id,)
    ).fetchone()

    if candidate is None:
        return None

    (
        entity_id,
        source,
        business_name,
        business_address,
        candidate_country
    ) = candidate

    candidate_country_norm = normalize_text(
        candidate_country
    )

    country_match = (
        country != ""
        and candidate_country_norm == country
    )

    # --------------------------------------------------------
    # If country doesn't match, no need to check other blocks
    # --------------------------------------------------------

    if not country_match:

        return {
            "candidate_id": candidate_id,
            "source": source,
            "business_name": business_name,
            "business_address": business_address,
            "country": candidate_country,
            "country_match": False,
            "prefix_hit": False,
            "first_token_hit": False,
            "address_token_hits": [],
            "total_address_hits": 0
        }

    # --------------------------------------------------------
    # 1. NAME PREFIX
    # --------------------------------------------------------

    prefix_hit = False

    if name:

        prefix = name[:4]

        result = conn.execute(
            """
            SELECT 1
            FROM name_prefix_index
            WHERE block_key = ?
              AND entity_id = ?
            LIMIT 1
            """,
            (
                country + "|" + prefix,
                candidate_id
            )
        ).fetchone()

        prefix_hit = result is not None

    # --------------------------------------------------------
    # 2. FIRST TOKEN
    # Same logic as V3
    # --------------------------------------------------------

    first_token_hit = False

    if name:

        tokens = [
            token
            for token in name.split()
            if len(token) >= 3
        ]

        if tokens:

            first_token = sorted(
                set(tokens),
                key=len,
                reverse=True
            )[0]

            result = conn.execute(
                """
                SELECT 1
                FROM first_token_index
                WHERE block_key = ?
                  AND entity_id = ?
                LIMIT 1
                """,
                (
                    country + "|" + first_token,
                    candidate_id
                )
            ).fetchone()

            first_token_hit = result is not None

    # --------------------------------------------------------
    # 3. ADDRESS TOKENS
    # --------------------------------------------------------

    address_token_hits = []

    if address:

        address_tokens = [
            token
            for token in set(address.split())
            if len(token) >= 5
            and not token.isdigit()
        ]

        address_tokens.sort(
            key=len,
            reverse=True
        )

        # IMPORTANT:
        # Instead of querying every token independently,
        # fetch all candidate address blocks ONCE.

        candidate_address_blocks = conn.execute(
            """
            SELECT block_key
            FROM address_token_index
            WHERE entity_id = ?
            """,
            (candidate_id,)
        ).fetchall()

        candidate_address_blocks = {
            str(row[0])
            for row in candidate_address_blocks
        }

        for token in address_tokens[:8]:

            block_key = country + "|" + token

            if block_key in candidate_address_blocks:
                address_token_hits.append(token)

    # --------------------------------------------------------
    # RETURN
    # --------------------------------------------------------

    return {
        "candidate_id": candidate_id,
        "source": source,
        "business_name": business_name,
        "business_address": business_address,
        "country": candidate_country,
        "country_match": country_match,
        "prefix_hit": prefix_hit,
        "first_token_hit": first_token_hit,
        "address_token_hits": address_token_hits,
        "total_address_hits": len(address_token_hits)
    }


# ------------------------------------------------------------
# 2. ANALYZE MISSED MATCHES
# ------------------------------------------------------------

step7_records = []

total_missed = len(missed_df)

print(
    "Total missed matches to analyze:",
    total_missed
)

for idx, missed_row in missed_df.iterrows():

    s1_id = str(missed_row["s1_id"])
    missing_id = str(missed_row["missing_id"])

    # --------------------------------------------------------
    # Retrieve S1 row
    # --------------------------------------------------------

    s1_match = s1_eval_correct[
        s1_eval_correct["entity_id"].astype(str) == s1_id
    ]

    if len(s1_match) == 0:
        continue

    s1_row = s1_match.iloc[0]

    # --------------------------------------------------------
    # Block evidence
    # --------------------------------------------------------

    evidence = get_block_evidence_v3_fast(
        s1_row,
        missing_id
    )

    if evidence is None:
        continue

    record = {
        "s1_id": s1_id,
        "s1_name": s1_row["business_name"],
        "s1_address": s1_row["business_address"],
        "s1_country": s1_row["country"],
        "missing_id": missing_id,
        **evidence
    }

    step7_records.append(record)

    # Progress
    if (idx + 1) % 5 == 0 or idx + 1 == total_missed:
        print(
            f"Analyzed {idx + 1}/{total_missed}"
        )


# ------------------------------------------------------------
# 3. CREATE DATAFRAME
# ------------------------------------------------------------

step7_df = pd.DataFrame(step7_records)


# ------------------------------------------------------------
# 4. CLASSIFY MISSED MATCHES
# ------------------------------------------------------------

def classify_miss_v3(row):

    if not row["country_match"]:
        return "COUNTRY_MISMATCH"

    if (
        row["prefix_hit"]
        or row["first_token_hit"]
        or row["total_address_hits"] > 0
    ):
        return "BLOCK_FOUND_BUT_RANKED_OUT"

    return "NO_EXISTING_BLOCK_HIT"


if len(step7_df) > 0:

    step7_df["reason"] = step7_df.apply(
        classify_miss_v3,
        axis=1
    )


# ------------------------------------------------------------
# 5. SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 7 COMPLETE")
print("=" * 70)

print(
    "Total missed matches analyzed:",
    len(step7_df)
)

if len(step7_df) > 0:

    print("\nReason breakdown:")

    print(
        step7_df["reason"].value_counts()
    )

    print("\nBlock evidence summary:")

    print(
        "Prefix hits:",
        step7_df["prefix_hit"].sum()
    )

    print(
        "First-token hits:",
        step7_df["first_token_hit"].sum()
    )

    print(
        "Address hits:",
        (step7_df["total_address_hits"] > 0).sum()
    )


# ------------------------------------------------------------
# 6. SAVE RESULTS
# ------------------------------------------------------------

import os

os.makedirs(
    "analysis",
    exist_ok=True
)

step7_output = (
    "analysis/missed_match_analysis_step7.csv"
)

step7_df.to_csv(
    step7_output,
    index=False
)

print("\nSaved Step 7 results to:")
print(step7_output)

Starting optimized Step 7...
Total missed matches to analyze: 21
Analyzed 5/21
Analyzed 10/21
Analyzed 15/21
Analyzed 20/21
Analyzed 21/21

======================================================================
STEP 7 COMPLETE
======================================================================
Total missed matches analyzed: 21

Reason breakdown:
reason
BLOCK_FOUND_BUT_RANKED_OUT    18
NO_EXISTING_BLOCK_HIT          3
Name: count, dtype: int64

Block evidence summary:
Prefix hits: 12
First-token hits: 0
Address hits: 6

Saved Step 7 results to:
analysis/missed_match_analysis_step7.csv